### ISSUE TITLE
Make a Jupyter Notebook tutorial for Inverse Kinematics and PSO

### ISSUE THREAD

**Issue by ljvmiranda921** [ljvmiranda921/pyswarms#136]
The idea is simple, implement a Jupyter notebook tutorial for inverse kinematics using PySwarms. I already have a tutorial (using natively-written PSO) in [this blog](https://ljvmiranda921.github.io/notebook/2017/02/04/inverse-kinematics-pso/). It might be nice to have a PySwarms equivalent. You just need to follow that tutorial, and swap everything in with PySwarms.

A good template can be found [here](https://github.com/ljvmiranda921/pyswarms/tree/development/examples)

Notes: Please work on the `development` branch. You can find a good StackOverflow question [here](https://stackoverflow.com/questions/38564473/how-to-fork-a-branch-and-not-the-repository).

**Comment by ljvmiranda921** [comment]
Hey @whzup ! Welcome!

No one's working on this and sure this one's yours :+1:  Be sure to fork the `development` branch and simply start the notebook inside the `examples/` directory :smile: 

If you have any questions (the github process in general, on inverse kinematics, etc.), do not hesitate to ping us!

**Comment by whzup** [comment]
Thanks a lot!
I have a question regarding the function that is to be optimized. In the [gist](https://gist.github.com/ljvmiranda921/7d8c48da0aa7565f0b3c01d7c951c5e9) to your blog post on row 43 of roboticArm.py you use `np.array([Etip[0,3],Etip[1,3],Etip[2,3]])` as the position function, why is it that the position is exactly the third column of the matrix? Also, I'm guessing that `Etip` is the transformation matrix for the end tip so that if you multiply it by a vector the position of the end tip would be the result, or am I wrong with that?

**Comment by ljvmiranda921** [comment]
Hi @whzup !

Awesome questions! Made me review my robotics basics again. :laughing:  So, for a Denavit Hartenberg (D-H) transformation matrix, the values in the fourth column (we start indexing by 0) describes the [translation from axis x to axis y (Check the last sentence in this link)](https://en.wikipedia.org/wiki/Denavit%E2%80%93Hartenberg_parameters#Denavit%E2%80%93Hartenberg_matrix).  That's why we are only taking those values.

Imagine your elbow joint as axis x and your wrist joint as axis y. If you want to know how your *wrist joint translates with respect to your elbow joint*, you compute the D-H matrix by doing a dot-product:

```
import numpy as np
transform_matrix_from_elbow_to_wrist = np.dot(elbow_joint, wrist_joint)
```

The result is a 4 x 4 matrix that we now know as the D-H transformation matrix. But what if we want to know how the *end-tip of our index finger translates with respect to our elbow joint*? Then, we successively compute the transformation matrix from elbow to wrist, then wrist to index finger tip. Same reason why there 's a succession of `np.dot`s to obtain `Etip`.

> I'm guessing that Etip is the transformation matrix for the end tip so that if you multiply it by a vector the position of the end tip would be the result, or am I wrong with that

In hindsight, I think that my variable name is misleading. You are right that the Etip is the transformation matrix from the zeroth-axis to the end-tip. Although I am not sure about multiplying a vector to find the end-tip position. Usually we just obtain the three values in the fourth column.

**Comment by whzup** [comment]
Thanks for the fast response. Really interesting to learn some things about robots on the fly 😋.
I have some other issues though:

1. The `pyswarms.singleGlobalBestPSO` class creates an array of length `n_particles` with each element being an array of the six parameters. I think this deliberate but it kind of complicates the function for the transformation matrix. I more or less copied your version of the function.

2. Is there a way to include a "target" in the `pyswarms.singleGlobalBestPSO` class such that I can just feed it the function and the target or do I have to manually add this in the optimization function? Alternatively, can the `pyswarms.singleGlobalBestPSO` class take a function with more than one argument as an input for the optimization? I have been looking around in the source code but it seemed to me that it only works with functions that only take one input.

For lack of a better alternative, here a picture of my code (copied into IDLE from the notebook)
![pyswarms_notebook](https://user-images.githubusercontent.com/39431903/41733749-280f3234-7585-11e8-911b-ec5d74e4f56e.PNG)

Thanks for the help thus far. I very much appreciate such a welcoming atmosphere!

**Comment by whzup** [comment]
Thanks for the answers! I think I've got a solid first version of the tutorial that can be added to the repo. I am not quite sure how to create a pull request without destroying something 😋. As you suggested I forked the development branch (using Github Desktop) and worked in there.

**Comment by bradahoward** [comment]
Being able to parameterize the objective function is really useful to me.  I got this to work using `**kwargs` and was about ready to submit a PR when i saw this discussion.  Do you guys mind if submit one?

**Comment by ljvmiranda921** [comment]
Hi @bradahoward ! Yes please feel free to open a PR. But I'd recommend you to open an Issue first so can keep a history of all things happening in this project :smile: 

While you're at it, I'm wondering if it's better to use `*args` than `**kwargs`. Would you mind investigating that as well and check which one works in a usability standpoint?
