### ISSUE TITLE
Boundary Conditions

### ISSUE THREAD

**Issue by jolayfield** [ljvmiranda921/pyswarms#150]
High-dimensional searches with the current bounds conditions result in a lot of lost optimization steps where many particles do not move.  

Multiple solutions exist to deal with these issues. We want to implement reflective boundary conditions that will keep the particle within the bounds in a way that still samples the whole parameter space.

**Comment by ljvmiranda921** [comment]
Ok, interesting. I’ve been reading about reflective boundary conditions and it seems a nice feature to have. Looking forward to your pull request! :) Don’t hesitate to ask questions if you’re stuck :)

**Comment by jolayfield** [comment]
Thanks.  I would like to ask a few questions:

1) Is it possible/advisable for us to add a third option to the tuple for bounds so that it would look like  (lb, up, bound_type)?  Can we make these kinds of decisions as they seem best to us or is it better to ask first so that we don't conflict with other ongoing work?
  
2) I am not exactly sure how to run/make the test suite.  I tried to run the options found on the contributions page, but was not sure whether I implemented them properly.  Is it better to hash this out now or wait until we are ready to merge the code?  

3) Is this the appropriate place to ask these questions?

Thanks

**Comment by ljvmiranda921** [comment]
Hi @jolayfield ! Any updates on this?

We're planning a v.0.3.0 release by the end of August. If this feature won't make it next month, we'll just insert this feature on v.0.4.0. There's no rush, what you just need to do is to *update your own master branch*. 

We're here to help you anytime!

**Comment by jolayfield** [comment]
Thanks.  We just got a working implementation yesterday with my research student.  I think there is still some testing to do and we will need to cleanup the input but it is coming along.  We will followup when we are sure that things are working properly (hopefully in the next few weeks).

**Comment by ljvmiranda921** [comment]
This has been a bit stale, closing this for now. I'll open this up again if there are already updates :+1:
