### ISSUE TITLE
Swarm visualization for different topologies

### ISSUE THREAD

**Issue by whzup** [ljvmiranda921/pyswarms#156]
The goal is to have Jupyter Notebook where different topologies traversing a fairly difficult objective function are visualized. As a reference for how it should look see the [README](https://github.com/ljvmiranda921/pyswarms/blob/master/README.md) or the [visualization example](https://pyswarms.readthedocs.io/en/master/examples/visualization.html#plotting-in-3-d-space). There is also a [discussion in a former issue](https://github.com/ljvmiranda921/pyswarms/issues/148#issuecomment-401539562) about this topic.

Possible things to include in this visualization are:

* The behaviour of different topologies
* Differences in the swarm behaviour for extreme social or cognitive parameters
* Your own ideas😋

I guess this is a very demanding first contribution so if you have any question don't hesitate 😄.
I recommend using the [Anaconda distribution for Python](https://www.anaconda.com/download/). If you use Anaconda you can follow the instructions [here](https://pyswarms.readthedocs.io/en/master/api/pyswarms.utils.environments.html) if you have don't have the `ffmpeg` package and the instructions for getting started in the [CONTRIBUTING file](https://github.com/ljvmiranda921/pyswarms/blob/master/CONTRIBUTING.rst) as well. (don't forget to open the `cmd` as an administrator on Windows so you can install packages without problems)

Notes: Please work on the development branch. You can find a good StackOverflow question [here](https://stackoverflow.com/questions/38564473/how-to-fork-a-branch-and-not-the-repository). For a more advanced guide to the GitHub workflow, there is [this cheatsheet](https://gist.github.com/Chaser324/ce0505fbed06b947d962) available.

See also: #148

**Comment by whzup** [comment]
Since this issue is quite stale and there seems to exist no interest on behalf of first timers I'll take this issue.

**Comment by stevenbw** [comment]
Hi @whzup !
Do you need some help reviving this issue?

**Comment by whzup** [comment]
@stevenbw Thanks for the offer! 💯
I don't think it's something that is urgent at the moment. And we probably have to do this ourselves. We had it as a first-timers issue for over a month and no one seemed interested. I have started a Jupyter notebook for it in [my fork](https://github.com/whzup/pyswarms/blob/topology-vis/examples/how_pso_topologies_behave_in_pyswarms.ipynb) if you want to have a look at it 😄.

**Comment by ljvmiranda921** [comment]
Closing stale and low-priority issues
