### ISSUE TITLE
Fix plotter module 

### ISSUE THREAD

**Issue by jayspeidell** [ljvmiranda921/pyswarms#167]
* PySwarms version: 0.20
* Python version: 3.6
* Operating System: Linux

### Description

1. The designer class in formatters.py is used for 3D graphing, but the default label list attribute only includes two axes. This causes an index out of range error. 

2. The delta attribute of the Mesher class in formatters.py is 0.001. This is too detailed and can lead to mesher objects that are large enough to cause memory errors on most computers. 0.1 will give the same level of detail with much less memory usage. 

3. The colormap attribute is hardcoded, so there's no way for the user to choose their own. 

### What I Did

I've already made updates to the code addressing these issues and will make a pull request soon.

**Comment by ljvmiranda921** [comment]
Conversation can be found in #165
