### ISSUE TITLE
Deprecation warnings by matplotlib

### ISSUE THREAD

**Issue by whzup** [ljvmiranda921/pyswarms#169]
When running all the tests `matplotlib` return deprecation warnings:

```python
============================== warnings summary ===============================
tests/utils/plotters/test_plotters.py::test_plot_cost_history_return_type[cost_history]
  c:\users\aaron\appdata\local\programs\python\python37-32\lib\site-packages\matplotlib\cbook\__init__.py:2347: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if isinstance(obj, collections.Iterator):
  c:\users\aaron\appdata\local\programs\python\python37-32\lib\site-packages\matplotlib\cbook\__init__.py:2364: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    return list(data) if isinstance(data, collections.MappingView) else data
```

We should fix this.

**Comment by ljvmiranda921** [comment]
Hmmm, I'm clueless on how to fix this...
What should be done? Bump matplotlib version?

**Comment by whzup** [comment]
Maybe changing the code to collections.abc.Iterator and
collections.abc.MappingView might do the trick.

Lj Miranda <notifications@github.com> schrieb am Di., 17. Juli 2018, 06:52:

**Comment by ljvmiranda921** [comment]
I don't remember using `collections.abc.Iterator` nor `collections.abc.MappingView` in my modules. Perhaps the Deprecation warning is not for PySwarms but on the `matplotlib` module itself? 
[This](https://github.com/ljvmiranda921/pyswarms/blob/development/tests/utils/plotters/test_plotters.py#L12) maybe the culprit but I really don't know...

Are you running development inside a virtual environment? What is your `matplotlib` version?

**Comment by whzup** [comment]
Yes, I realized it as well hahaha. I use `pip` and just installed Python 3.7. Also, `matplotlib` might not have updated their packages to fit the new Python standard this might be the reason.

**Comment by ljvmiranda921** [comment]
I see. I’ll close this for now :+1: Thanks for the heads up!
