### ISSUE TITLE
setup.py does throws a UnicodeDecodeError

### ISSUE THREAD

**Issue by whzup** [ljvmiranda921/pyswarms#174]
**Describe the bug**
The `setup.py` file throws a `UnicodeDecodeError`:
```
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    readme = readme_file.read()
  File "Python\Python37-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 11427: character maps to <undefined>
```

**To Reproduce**
Run the `setup.py` file to install `pyswarms`:

```
python setup.py install
```

**Expected behaviour**
No `UnicodeDecodeError` 😄.

**Environment (please complete the following information):**
 - OS: Windows
 - PySwarms Version v0.2.1
 - Python Version 3.7.0

**Additional context**
Not a big deal there is a [StackOverflow question](https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character) with the solution to this problem. PR is coming.

**Comment by ljvmiranda921** [comment]
PySwarms hasn’t been tested in Python 3.7. Can you try setting up a virtualenv for 3.4, 3.5, and 3.6? That should work because our tests are passing and travis performs the steps you did above.

Let’s do 3.7 and 0.4.0 :) No need to rush
