### ISSUE TITLE
`ValueError` when running the GeneralOptimizer with a `Pyramid` topology

### ISSUE THREAD

**Issue by whzup** [ljvmiranda921/pyswarms#183]
**Describe the bug**
The `Pyramid` topology throws the following error when ran in the `GeneralOptimizerPSO` (only in some cases):
```python
\AppData\Local\Programs\Python\Python37-32\lib\site-packages\src\pyswarms\pyswarms\backend\topology\pyramid.py", line 75, in <listcomp>
    [swarm.pbest_cost[self.neighbor_idx[i]].argmin() for i in range(len(self.neighbor_idx))]
ValueError: attempt to get argmin of an empty sequence
```

**To Reproduce**
Steps to reproduce the behaviour:

- Run this script in the current `development` version:
```python
import pyswarms as ps
import numpy as np
from pyswarms.utils.functions import single_obj as fx
from pyswarms.backend.topology import Random, Pyramid, Ring, Star, VonNeumann

# Set-up hyperparameters
options = {"c1": 2, "c2": 2, "w": 0.5, "k": 4, "p": 2, "r":1}
iters = 1000
dim = 5
bounds = (np.repeat(-5.12, dim), np.repeat(5.12, dim))
topology = Pyramid(static=False)
optimizer = ps.single.GeneralOptimizerPSO(n_particles=10, dimensions=dim, options=options, bounds=bounds, topology=topology)
best_cost, best_pos = optimizer.optimize(fx.sphere_func, iters=iters, verbose=0, print_step=1)
```

**Environment:**
 - OS: Windows
 - PySwarms Version development
 - Python Version 3.7.0

**Additional context and bug fix**
I investigated this bug and it turns out this might be a precision error in the `Delaunay` class which is used in the `Pyramid` topology to compute the neighbours. It seems that if two particles are too close to each other the triangulation isn't computed correctly. This leads to some particles not having any neighbours, that is, their array in the `neighbour_idx` attribute being empty. I looked up the [scipy documentation](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.spatial.Delaunay.html) which led me to the [qhull documentation](http://www.qhull.org/html/qdelaun.htm). I suggest that we change this line:

```python
pyramid = Delaunay(swarm.position)
```

to the following:

```python
pyramid = Delaunay(swarm.position, qhull_options="QJ0.001 Qbb Qc Qx")
```
What the options do:

- `QJ0.001`: randomly joggle particles in the range [-0.001,0.001], that is, the particles are randomly pushed apart if they are in too narrow of a space. This makes sure that the particles don't get too close together.
- `Qbb`: improves numeric precision. I'm not sure if this is necessary but I included it because it is labelled as default in the scipy doc.
- `Qc`: keep coplanar points with the nearest facet. I'm not exactly sure what this means, but it's in the defaults so I included it.
- `Qx`: exact pre-merges (allows coplanar facets). Again not sure what it does but it's in the defaults.

The `Qz` option (also in the defaults), together with the 4 above, leads to a `MemoryError`.
For more precise information visit [this page](http://www.qhull.org/html/qh-optq.htm#Qc).

I've run the `optimize` method about 300 times to make sure this fixes the error. And it apparently does! 😄 

I can do a separate PR for this or I can include it in the cleanup PR I've already made. What do you think, @ljvmiranda921?

**Comment by ljvmiranda921** [comment]
Hi @whzup!

Yes. Please add to cleanup PR and document the qhull options in the Pyramid class docstring. 

Let’s give ourselves 2 weeks to look for edge case errors and bugs in the new topologies. Just keep adding them to the same PR you had. After 
August 12, let’s lock that PR and prepare for merge.

**Comment by whzup** [comment]
Sure! Made a new PR and added the documentation for it 👍 I'm going to try on breaking the topologies 😄
