### ISSUE TITLE
CUDA implematation

### ISSUE THREAD

**Issue by dhariyalbhaskar** [ljvmiranda921/pyswarms#19]
Does this PSO supports CUDA?

**Comment by ljvmiranda921** [comment]
Hi, @dhariyalbhaskar , as of now, there's no support for CUDA in this library yet.

For the short-term, I'm planning to use the [multiprocessing](https://docs.python.org/2/library/multiprocessing.html) module to atleast perform parallelization and more efficient computation.

If you're interested in contributing CUDA support, then it would be really nice! 😄
