### ISSUE TITLE
Add black fmt: off tags to test n-dimensional arrays

### ISSUE THREAD

**Issue by ljvmiranda921** [ljvmiranda921/pyswarms#201]
**Describe the bug**
The problem is that whenever we have a multidimensional array for test-cases, black formats them
"vertically", resulting to a very high LOC and uglier code. See [this issue](https://github.com/ambv/black/issues/440)

**To Reproduce**
```
$ black tests/
$ vim tests/backend/topology/test_von_neumann.py
```

Then check `test_delannoy_numbers` and observe how the n-dim array is formatted.

**Expected behavior**

It's better to retain the current formatting. 

**Environment (please complete the following information):**
 - OS: [e.g. Linux] Linux
 - Version [e.g. Ubuntu 16.04] Ubuntu 16.04
 - PySwarms Version [e.g. v.0.2.0] v.0.3.0
 - Python Version [e.g. 3.6.X] 3.6.X

**Additional context**

We can easily solve this by using  `fmt: off` followed by `# fmt: on` on specific parts of the code. However, we also need to identify parts of the code where we need to use this formatting.

**Comment by whzup** [comment]
To be honest this looks like a really ugly solution to me :confused:. This would be better off as an option in the `black` module instead of something that has to be done manually.

**Comment by ljvmiranda921** [comment]
For now this is what we can only do. Using external files to export our predefined numpy arrays seems to convolute everything. Unless there's a better way to remove the n-dimensional arrays that we have, maybe `hypothesis` can make our predefined arrays more generalized (and reproducible?)
