### ISSUE TITLE
Make a Jupyter notebook tutorial for the analysis of a simple circuit

### ISSUE THREAD

**Issue by whzup** [ljvmiranda921/pyswarms#202]
## Goal
PSO can be utilized in a wide variety of fields. To broaden our collection of tutorials, we'd like to have another example where we analyse a simple circuit with PSO. For some inspiration, you can visit the [example section](https://github.com/ljvmiranda921/pyswarms/tree/master/examples). I propose that, for the beginning, we start by analysing the circuit shown below. It has a resistor and a diode. **The end-goal is to have a nice Jupyter notebook that goes through the whole process of writing this optimization program.**
## Method
![circuit](https://user-images.githubusercontent.com/39431903/43938822-29aaf9b8-9c66-11e8-8e54-01530db005c6.png)
As there are many models for diodes, let us use a more realistic one (a simplified Shockley equation) for this tutorial:

<a href="https://www.codecogs.com/eqnedit.php?latex=I&space;=&space;I_s&space;e^{\frac{v_D}{v_T}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?I&space;=&space;I_s&space;e^{\frac{v_D}{v_T}}" title="I = I_s e^{\frac{v_D}{v_T}}" /></a>

where:
 - <a href="https://www.codecogs.com/eqnedit.php?latex=I" target="_blank"><img src="https://latex.codecogs.com/gif.latex?I" title="I" /></a>:  diode current
- <a href="https://www.codecogs.com/eqnedit.php?latex=I_s" target="_blank"><img src="https://latex.codecogs.com/gif.latex?I_s" title="I_s" /></a>: reverse bias saturation current
- <a href="https://www.codecogs.com/eqnedit.php?latex=v_D" target="_blank"><img src="https://latex.codecogs.com/gif.latex?v_D" title="v_D" /></a>: diode voltage
- <a href="https://www.codecogs.com/eqnedit.php?latex=v_T" target="_blank"><img src="https://latex.codecogs.com/gif.latex?v_T" title="v_T" /></a>: thermal voltage (use 25.3 mV in this tutorial)

to use it in the tutorial I'd recommend to solve for <a href="https://www.codecogs.com/eqnedit.php?latex=v_D" target="_blank"><img src="https://latex.codecogs.com/gif.latex?v_D" title="v_D" /></a>:

<a href="https://www.codecogs.com/eqnedit.php?latex=v_D&space;=&space;v_T&space;\log{\left&space;|\frac{I}{I_s}\right&space;|}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?v_D&space;=&space;v_T&space;\log{\left&space;|\frac{I}{I_s}\right&space;|}" title="v_D = v_T \log{\left |\frac{I}{I_s}\right |}" /></a>

Using the Kirchhoff voltage law we get this:

<a href="https://www.codecogs.com/eqnedit.php?latex=U&space;=&space;v_D&space;&plus;&space;v_R" target="_blank"><img src="https://latex.codecogs.com/gif.latex?U&space;=&space;v_D&space;&plus;&space;v_R" title="U = v_D + v_R" /></a>

where <a href="https://www.codecogs.com/eqnedit.php?latex=v_R" target="_blank"><img src="https://latex.codecogs.com/gif.latex?v_R" title="v_R" /></a> denotes the voltage over the resistor. We can restructure it to be our cost function <a href="https://www.codecogs.com/eqnedit.php?latex=c" target="_blank"><img src="https://latex.codecogs.com/gif.latex?c" title="c" /></a> (optimally it is 0) for the optimization:

<a href="https://www.codecogs.com/eqnedit.php?latex=c&space;=&space;\left&space;|U-v_D-v_R\right&space;|" target="_blank"><img src="https://latex.codecogs.com/gif.latex?c&space;=&space;\left&space;|U-v_D-v_R\right&space;|" title="c = \left |U-v_D-v_R\right |" /></a>

The absolute value is necessary because we don't want to obtain negative currents. If we write this more verbosely we see that the current <a href="https://www.codecogs.com/eqnedit.php?latex=I" target="_blank"><img src="https://latex.codecogs.com/gif.latex?I" title="I" /></a> **is the parameter we want to optimize**:

<a href="https://www.codecogs.com/eqnedit.php?latex=c&space;=&space;\left&space;|&space;U&space;-&space;v_T&space;\log{\left&space;|&space;\frac{I}{I_s}&space;\right&space;|}&space;-&space;RI&space;\right&space;|" target="_blank"><img src="https://latex.codecogs.com/gif.latex?c&space;=&space;\left&space;|&space;U&space;-&space;v_T&space;\log{\left&space;|&space;\frac{I}{I_s}&space;\right&space;|}&space;-&space;RI&space;\right&space;|" title="c = \left | U - v_T \log{\left | \frac{I}{I_s} \right |} - RI \right |" /></a>

These are some sample values for the other parameters:
- <a href="https://www.codecogs.com/eqnedit.php?latex=U" target="_blank"><img src="https://latex.codecogs.com/gif.latex?U" title="U" /></a> : 10 V
- <a href="https://www.codecogs.com/eqnedit.php?latex=I_s" target="_blank"><img src="https://latex.codecogs.com/gif.latex?I_s" title="I_s" /></a> : 9.4 pA
- <a href="https://www.codecogs.com/eqnedit.php?latex=R" target="_blank"><img src="https://latex.codecogs.com/gif.latex?R" title="R" /></a> : 100 Ohm

Of course, if you know an alternative way to solve this or you have any questions about the issue don't hesitate to write a comment! **I'm looking forward to seeing a first-timer writing this Jupyter notebook!** 💯

## Notes
Please work on the development branch. You can find a good StackOverflow question about forking [here](https://stackoverflow.com/questions/38564473/how-to-fork-a-branch-and-not-the-repository). For a more advanced beginner guide to the GitHub workflow, there is [this cheatsheet](https://gist.github.com/Chaser324/ce0505fbed06b947d962) available. It is quite detailed and gives a simple overview.

**Comment by pranav1698** [comment]
Heya ljvmiranda921, 
I have started working on open source recently 
I would like to contribute on this issue

**Comment by pranav1698** [comment]
Can I have a detailed guide to how to make a jupyter notebook using python
Also, I have been getting this error:
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    with open("README.md", encoding="utf8") as readme_file:
TypeError: 'encoding' is an invalid keyword argument for this function
when I am trying to build pyswarms in my local machine

**Comment by ljvmiranda921** [comment]
Hi @pranav1698 , welcome to PySwarms! 

I will hand you over to @whzup for this, since he’s more knowledgeable on this side of the codebase :) 

As for your setup problem, what is your Python version again? :)

**Comment by whzup** [comment]
Hello @pranav1698, welcome from my side as well 😄 🎊 🎉 
**Regarding the creation of a Jupyter notebook:**
1. Install jupyter notebook via pip (may require `sudo` on Unix or administrator rights on Windows):
```
pip install jupyter notebook
```
2. Navigate to the `pyswarms/examples` folder in your command line and type:
```
jupyter notebook
```
This will open the Jupyter notebook interface in your default browser. You'll see that it automatically opened the folder in which you executed the command `jupyter notebook`. Now you can create a new Jupyter notebook by clicking on *New* in the top right corner (choose *Python 3*).
You can then start working on the notebook. In the tool bar you will find a drop down menu with the default set to *Code* you can choose *Markdown* ([here you can find a Markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)) to write text and *Code* to write code. :+1:
The ```In [ ]``` on the left side indicates the order in which the cells were run. If it is empty it hasn't been run yet, if it contains a number `n` it's the `n`th cell that was run. To run a cell click on *Run* 😄 The kernel is the current "shell" your cells are running in. If you restart the kernel you restart the scope in which the cells were run so you have to rerun them again. For a more detailed description you can also consult the [Jupyter documentation](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html)

You can use the [Inverse Kinematics Tutorial](https://github.com/ljvmiranda921/pyswarms/blob/master/examples/inverse_kinematics.ipynb) as a reference for the layout and formatting (you can open them in the Jupyter notebook interface in your browser and doubleclick on the *Markdown* cells to see the formatting).

**Regarding your issue with the `setup.py`:**
It seens like you use Python 2.X. The `open()` function does not have an encoding parameter in Python 2 and `pyswarms` does not support Python 2 anymore so make sure you use Python 3 for the development. If you use a Unix system try installing it using `python3` instead of `python` since on some Linux distributions `python` is an alias for `python2` (e.g. OpenSUSE):
```python3 setup.py install```

If you use Windows install a Python 3 version. You can have different Python versions on your PC without any problems.

In case you have any question don't hesitate to ask in this thread 😃 In the issue description above you find more information about the GitHub workflow in case you need them (I use them as well). I appreciate your commitment to this issue and hope you have fun working on it! 😄 🥇

**Comment by pranav1698** [comment]
Thanks for the help
Sure, The concept is new and unique henceforth I will try my best to solve it

**Comment by pranav1698** [comment]
Hey again,
I think the circuit-diagram is a bit of confusing,
Seeing the diagram,  If the arrow on the voltage source U, I think this  points from lower voltage to higher voltage (If it is not the direction of electric field) so this should be the direction of current but  the direction of current I is opposite.

**Comment by whzup** [comment]
Hello, @pranav1698. Good question!

There are two types of electric components: active and passive ones. For passive components it is true that the arrow of the voltage points from the lower voltage to the higher voltage and the current arrow points in the same direction. This is because they "**consume**" power, that is if voltage and current have the same sign the power is always positive. Resistors and silicium diodes are examples for passive elements.

Contrary to passive elements are active ones. They have the voltage arrow point from the higher voltage to the lower voltage. As you may imagine this is because active elements "**produce**" power, that is the power is always negative (voltage and current always have different signs).
The voltage source is exactly one of these active elements and thus the voltage arrow points from the higher voltage node to the lower voltage node.

This all is a convention, though. If you want to read more about it's called *Passive sign convention*.

**Comment by pranav1698** [comment]
Hello whzup,
I have on some of the changes locally, so can I create a pull request for my working branch 
So that you can see if they are fine.

**Comment by whzup** [comment]
@pranav1698, sure go ahead! Make sure to update your branch before doing the PR (you can use the links in the issue description for information on how to do that).

There is actually no target vector in this optimization (I guess you're referring to the Inverse Kinematics tutorial by saying target vector). I think it's not clear from the description what it means to analyse a circuit, that's a mistake on my part 😕 The goal of the analysis of this circuit is to find out what the current `I` is. The cost function `c` is only dependent on the parameter `I`. The other ones (`U`, `vT`, `Is` and `R`) are all constant values. Hence, this is a one dimensional optimization problem for the parameter `I` (i.e. your optimization scalar). So you don't have a target vector that you have to optimize to, you just want to minimize the cost function `c`.
Regarding the "how to use it" question: You can write a cost function `c` which takes the current `I` as an input and returns a scalar (!) you can then use the [cost decorator](https://github.com/ljvmiranda921/pyswarms/blob/development/pyswarms/utils/decorators/decorators.py) to vectorize the cost function which makes it ready for the optimization.

I hope this answers your questions. If there are still things that are not clear just ask 😄.

**Comment by whzup** [comment]
Hey @pranav1698, excuse my late respone I'm on vacation and only have access to my laptop in the evening :smile:

The target of the particles in the swarm is the minimum of the function `c` (see above). We don't know this value though! So the particles memorise their personal best position (pbest) and the best position of all particles (gbest) in order to find the best position (minimum) in the search space. These two positions gbest and pbest are used as a reference for the particles. For a brief, more in-depth explanation look [here](https://pyswarms.readthedocs.io/en/master/api/pyswarms.single.html#module-pyswarms.single.global_best).

PSO is always used with mathematical functions. If you have a very basic function say for example `x^2` you can write it directly in your cost function:
```python
@pyswarms.cost
def my_cost_func(x):
    return x**2
```
If you have a more complex function like for example in the Inverse Kinematics tutorial it may be more sensible to make several helper functions so you don't cram full your cost function.

The value of `I` changes as the particles move around. While they move around they memorise the pbest and gbest and at the end of the optimization loop the best value that has been found by the swarm is returned.


I had a look at your PR and the next steps for you are:
1. Set up an optimization loop with `pyswarms` (you can use [this example](https://github.com/ljvmiranda921/pyswarms/blob/development/examples/basic_optimization.ipynb) as a reference for how this is achieved)
2. Write a cost function `c`. For example:
```python
@pyswarms.cost
def my_cost_func(x):
    cost = do_something(x)
    return cost
```
you can use the function `c` in the issue description for this one.

3. When the steps 1 and 2 work you can try to use the [`GeneralOptimizerPSO`](https://pyswarms.readthedocs.io/en/master/api/pyswarms.single.html#pyswarms-single-general-optimizer-module). It has almost the same API as the `GlobalBestPSO` except the fact that you have to pass a topology as an argument at initialization (see link for an example).

4. Describe the steps you made to write the optimisation in detail.

5. If you want to you can add some other experiments. For example you could [plot the cost history](https://github.com/ljvmiranda921/pyswarms/blob/development/examples/visualization.ipynb) or any idea that comes to your mind :smile: 

I hope I understood your questions and could answer them to your satisfaction if not feel free to let me know!

**Comment by pranav1698** [comment]
I am getting NameError when I am using
@pyswarms.cost
 It says; name 'pyswarms' is not defined
Is it because of the python version?

Also, I have made the commmits with the present changes? Please have a look..

**Comment by ljvmiranda921** [comment]
Hi @pranav1698 ,

> I am getting NameError when I am using @pyswarms.cost

It is because in the earlier cell, you already called:

```python
import pyswarms as ps
```

That's why it sets an alias to the pyswarms module. To call `pyswarms.cost`, just
say `ps.cost`. 

I think everything looks OK so far! Keep at it! :+1:

**Comment by pranav1698** [comment]
Hi @ljvmiranda921 ,
Nopes I am getting the same error with ps; I had tried that earlier too
Looks Like its the preoblem for the python version, as I am working on ubuntu and I cannot delete the default python version(2.7.15) as it is not suggested

**Comment by whzup** [comment]
Hello @pranav1698, it looks good until now! Let's focus on finishing the first draft. Afterwards we can focus on the details.
As for the `NameError`. It is probably because you didn't rerun the cells in which you define `pyswarms` (You define `import pyswarms as ps` in `In[17]` and use it in `In[2]` the number tells you the order in which you ran the cells this is important!). You already run the Jupyter notebook with Python 3.6.5 you don't need to do anything to your Python installation. In the menubar there should be a Kernel menu there you find the option "Restart kernel and run all cells" try running this. Although, make sure you use `@ps.cost` instead of `@pyswarms.cost` when you import it like that.

**Comment by whzup** [comment]
@aakritigupta0408 Welcome to pyswarms! Sure go ahead, it seems like the previous contributor gave up on this 🙈. If you have any questions feel free to ask. I'll gladly answer them as soon as I can 😄.

**Comment by whzup** [comment]
Hey, @abdurrehman11 thank you for your interest in pyswarms. Unfortunately, at the moment the development of this project is a bit stale as the owner of the repository is quite busy at work and I am going to study for my winter finals. If you feel like you could handle a PR for any of the open issues you can leave a comment there. Otherwise, maybe you and @aakritigupta0408 could jointly work on this Jupyter notebook here, what do you think? :smile:

**Comment by abdurrehman11** [comment]
Hey @aakritigupta0408 what do you think about this?

**Comment by miguelcocruz** [comment]
Is this still up for grabs?

**Comment by ljvmiranda921** [comment]
Hi @miguelcocruz , I think this is up for grabs now! Wanna make a PR?
