### ISSUE TITLE
Profiling the Topologies

### ISSUE THREAD

**Issue by whzup** [ljvmiranda921/pyswarms#206]
Since we have a solid number of new topologies now, it might be cool to have some kind of profile for every one of them. The questions now are:

- What experiments shall we conduct?
- Which parameters do we want to measure?
- How shall we represent our results? A text file? A Jupyter notebook?

I suggest using the [`cProfile` module](https://docs.python.org/3.7/library/profile.html). It offers a small amount of overhead and is deterministic so it creates very precise profiles.

**Comment by ljvmiranda921** [comment]
> What experiments shall we conduct?

1. We can measure how fast each topology converges wrt (a) number of particles, (b) objective function, and (c) various parameter settings.
2. So this becomes more of a benchmarking experiment. I imagine we can draw cost histories and see convergence rates etc.

> Which parameters do we want to measure?

Number of neighbors IMO is really important. We can also check what happens given a pure social or pure cognitive swarm (where either c1 or c2 is set to 0). I'll try to come up of an "experiment matrix" next weekend so that we know what parameters to fill-in.

> How shall we represent our results? A text file? A Jupyter notebook?

I vote for Jupyter notebooks, then we can also put this into ReadTheDocs. We can even put the results into a LaTeX file and upload to arxiv.

> I suggest using the cProfile module. It offers a small amount of overhead and is deterministic so it creates very precise profiles.

This looks good, although I'm not very familiar with this. I also see `pstats` being used in conjuction with cProfile. Wonder if it applies to our use-case.

**Comment by whzup** [comment]
@ljvmiranda921, that sounds nice! When I was mulling over this for a while, I had two ideas which are somewhat intertwined:

1. **A `neighbor_history` attribute:** We could insert the neighbours for every iteration into a `neighbor_history` attribute in the base class. This would just mean that we have to access the `neighbor_idx` array in the `topology.compute_gbest()` method. This would enable us to analyse how the neighbours change over time.

2. **A new feature for the `plotters` module:** Visualise the neighbours by drawing a line between two neighbours in the animation. To avoid drawing the lines twice, we can omit all the indices in an array of neighbours that are lower than the current index of the particle. This might become a bit messy for dynamic topologies but we could default it to `False`.

Regarding the `pStats` module, I have played around with it for a bit. It seems pretty good and you can generate a very nice output, although it did some weird things when I wrote the output in a file instead of printing it. Might be because of the Windows environment. I'll try it on Linux as well. I thought about using a decorator:
```python
@profile
optimizer.optimize(params)
```
in the profiling script so we can easily profile the functions when running, what do you think? We could even add this as a feature so users can profile it themselves.

**Comment by ljvmiranda921** [comment]
> A neighbor_history attribute: We could insert the neighbours for every iteration into a neighbor_history attribute in the base class. 

Looks pretty good! So we just build this similar to the previous history attributes right?

> A new feature for the plotters module: Visualise the neighbours by drawing a line between two neighbours in the animation.

Yes, this is a really nice option. We can turn this on/off when plotting. :+1:

**Comment by whzup** [comment]
> Looks pretty good! So we just build this similar to the previous history attributes right?

Yes, I think so. We just have to figure out a fast way to append the whole `numpy.array` I don't know if it is feasible to put it in another `numpy.array`. I'll do some research on that.

I'll try to write up a PR for the history and visualization feature this week.

**Comment by ljvmiranda921** [comment]
No idea yet, maybe we can do this at the end? I'm thinking of just a Jupyter notebook example actually. After merging #226 and #227 maybe we can focus on constrained opt first.

**Comment by whzup** [comment]
Yes, this might be a better idea. :+1: We could then include the constraint optimization also. Maybe, it'd be even better to wait until we have multi-objective optimisation done as well (?) So for the end of v.0.5.0.

**Comment by ljvmiranda921** [comment]
Closing stale and low-priority issues
