### ISSUE TITLE
Add Reporter module for logging

### ISSUE THREAD

**Issue by ljvmiranda921** [ljvmiranda921/pyswarms#209]
**Is your feature request related to a problem? Please describe.**

We can improve the [`console_utils.py`](https://github.com/ljvmiranda921/pyswarms/blob/master/pyswarms/utils/console_utils.py) module and abstract all of our logging methods inside a `Reporter` class. We do this because we want to achieve separation of concerns in our base classes. Our base swarm optimizers still setup the logging themselves, it's better to call a class that performs all logging-related tasks.

**Additional context**
Some things a `Reporter` can do:
1. Do logging and printing during the optimization process (log to console or to external file, etc.)
2. Profiling report of the run.

We use `reporter` for printing and logging:

```python
reporter = Reporter()

# We can log to console
reporter.log("Iter: {} | Cost: {}".format(iter, cost), log_to='console')
# or to an external file
reporter.log("Iter: {} | Cost: {}".format(iter, cost), log_to='file.txt')
```

We can then set a `log_output` attribute for high-level optimizers such as `GlobalBestPSO` (`str`, default is `console`). After optimization, we can use the `Reporter` class to access some statistics:

```python
self.reporter.get_summary()
```

The above method works similarly to [`console_utils.end_report`](https://github.com/ljvmiranda921/pyswarms/blob/master/pyswarms/utils/console_utils.py#L34), but formatted much nicely.

**Note:** API may still change

**Comment by whzup** [comment]
Do you think we could include an `@profile` decorator in the `Reporter` module? I was thinking about using it as a parameter in the `optimize` method but (1) it doesn't belong quite there and (2) it would be necessary to include it in every `optimize` method of every `optimizer` which is quite a lot of code to include.

**Comment by ljvmiranda921** [comment]
> Do you think we could include an @profile decorator in the Reporter module?

Yup you are correct, I'm planning to have the profiler as a decorator. This looks quite exciting!
