### ISSUE TITLE
Improve the topology test suite

### ISSUE THREAD

**Issue by whzup** [ljvmiranda921/pyswarms#211]
Since we had some issues with testing in the past, I propose that we include the [`hypothesis` module for Python](https://github.com/HypothesisWorks/hypothesis/tree/master/hypothesis-python) into our test suite. Side by side with the `pytest` module we're already running as it is [compatible with `pytest`](https://hypothesis.readthedocs.io/en/latest/supported.html). The `hypothesis` module allows us to cover a broader range in our parametrization and checks edge cases. As they say it on their page:
 > It lets you write tests which are parametrized by a source of examples, and then generates simple and comprehensible examples that make your tests fail. This lets you find more bugs in your code with less work.

It is quite powerful and might help us in finding bugs earlier.

**Comment by ljvmiranda921** [comment]
Looks interesting. :+1:  I have some questions:

- Can you give some example use-cases for `hypothesis` in relation to our current test suite? 
- Which parts of our test suite will `hypothesis` improve? 
- Can you give an example change you're going to implement?

**Comment by whzup** [comment]
I have to look deeper into it but what I can say at the moment is that could use it for almost any test case. You can choose a "range" of integers/floats/etc. you want to test and it will test it. You can even [create dictionaries](https://hypothesis.readthedocs.io/en/latest/data.html). This would be useful for the options dicts that we use. As for the improvement, it tests a broader range of values instead of only some random values we pick. Additionally, it saves the values that would yield a bug with enough information to recreate it.
I haven't looked deep enough into `hypothesis` yet to give an example but I believe we could implement it in probably more than 60% of the test functions.

**Comment by ljvmiranda921** [comment]
Sure, I would like to see a PR on this. I imagine that we can use this to generalize our fixtures and some tests. :+1:

**Comment by whzup** [comment]
It turned out the `hypothesis` module runs very slow and the code that we'd have to write for the tests was extremely incomprehensible. For comparison: one test with hypothesis takes as long as all the tests in the topology folder. If we'd scale this to the 500 tests we already have we'd easily reach 10-15 mins. We can't afford such a huge test suite in such a small project. At the moment I don't think its sensible to include it. But I have found another thing we could do. Instead of using an example swarm for the testing of the topologies, we could generate a swarm with the `bounds` and `options` we want it to have and test the properties (e.g. ` best_cost` is the minimum of all costs etc.) of every parameter.

**Comment by ljvmiranda921** [comment]
>  Instead of using an example swarm for the testing of the topologies, we could generate a swarm with the bounds and options we want it to have and test the properties (e.g. best_cost is the minimum of all costs etc.) of every parameter.

Yes this looks much better. If it makes our test suite much simpler (and less reliant on default, *very* contrived values), then go for it. :+1:

**Comment by whzup** [comment]
Hmm, I think I erred here. I thought we could just take the minimum of all the costs but the swarm actually only stores the best cost and position in addition to the current cost and position. Maybe we can add the `history` of a fixture optimizer to the tests so we can make sure the best cost is the best cost that has ever been found. What do you think?

**Comment by ljvmiranda921** [comment]
> ...add the history of a fixture optimizer to the tests so we can make sure the best cost is the best cost that has ever been found.

Sorry it's not yet clear to me. How is this different from our  [`*_opt_history()` fixtures](https://github.com/ljvmiranda921/pyswarms/blob/development/tests/optimizers/conftest.py#L17)? Can we reuse these fixtures for the problem? :+1:

**Comment by whzup** [comment]
Yes, exactly! But now we use it for the topology tests. We just have to return the history and the best cost/pos in the fixture so we can check if it really is the best that has ever been found. I'll go ahead and write this up. It's probably a small PR.
