### ISSUE TITLE
Visualise neighbors during optimization

### ISSUE THREAD

**Issue by whzup** [ljvmiranda921/pyswarms#212]
As described in #206 it'd be useful to have a feature where we can indicate a neighbour relationship in the `plotters` module's visualization output. First of all, we have to add a `neighbours` attribute to the History tuple. This then allows us to access the neighbours of every particle in every iteration. After that, we can use this information to draw lines between every two neighbours in the animation. This feature should be optional and off by default since it might become quite messy when used with dynamic topologies.

See also: #206

**Comment by ljvmiranda921** [comment]
Closing stale and low-prio issues. Please reopen it again if you wish to work on it again
