### ISSUE TITLE
Remove `_func` in all single-objective function names

### ISSUE THREAD

**Issue by ljvmiranda921** [ljvmiranda921/pyswarms#219]
Currently, our single-objective functions look like this:

```python
def sphere_func(x):
    """A sphere function"""
    j = x ** 2
    return j
```

We realized that it's much better to remove the `_func` part of the name for terseness:

```python
# Expected output
def sphere(x): # Just remove "_func!"
    """A sphere function"""
    j = x ** 2
    return j 
```

That's basically it!

## Where to apply the changes?
1. All single-objective functions reside in the `pyswarms/utils/functions/single_obj.py. Simply change the function names.
2. However, some function calls are present inside the `tests/` module. Hunt them down!
3. You also need to double-check our documentation in `pyswarms/docs/*` and `README.md`. Make sure that the API is up-to-date with our docs and examples!

If you have any questions, do not hesitate to ping us!

**Comment by nik1082** [comment]
Hello! I'd like to take a shot at this!

**Comment by ljvmiranda921** [comment]
Awesome @nik1082 ! This one's yours!

**Comment by ljvmiranda921** [comment]
Oops sorry, hey @nik1082 . Would it be fine if you can do this PR again? But this time checkout from the `development` branch. Merging with conflicts has been tricky for me lately, most especially that we applied branch protection for both our `development` and `master` branches. My bad, sorry for the trouble and thanks again!

**Comment by nik1082** [comment]
Done and done!
