### ISSUE TITLE
Add boundary handlers for stuck particles

### ISSUE THREAD

**Issue by ljvmiranda921** [ljvmiranda921/pyswarms#237]
**Is your feature request related to a problem? Please describe.**
There are some stuck particles as reported in #234 and #150 . This is related to `compute_position` waiving position updates whenever a particle will potentially end up out-of-bounds. There are standard ways to avoid this problem. The reflective bounds is one option, but the related PR is currently stale, so it may be important to create a general framework for handling the boundary problem.

**Describe the solution you'd like**
Create a set of handlers, such as a `BoundaryHandler`. Usage example:

Usage outside of the class

```python
# Usage outside of the class
from pyswarms.backend import operators as ops
from pyswarms.backend.handlers import BoundaryHandler

bh = BoundaryHandler(strategy="reflective") # And other arguments here if it's parameterized
ops.compute_position(swarm, bounds, handler=bh) 
```

Inside `BoundaryHandler`

```python
# Inside BoundaryHandler
class BoundaryHandler(object):
    def __call__(self, position, bounds, *args, **kwargs): # parameterized
        # Some logic here depending on the type of handler, for example:
        # (might be better as a dictionary with a string as key and callable as
        # its value)
        if self.strategy == "reflective":
            new_positions = self.reflective(position, bounds) # parameterized

    def reflective(self, position, bounds):
        """Some docstring here"""
        pass
```

How it will work in the backend:

```python
if handler:
    new_position = handler(swarm.positions, bounds)
```

**Comment by ljvmiranda921** [comment]
What do you think, @whzup

**Comment by whzup** [comment]
I like it! :smile: Let's do something like that.
Although, do you really think it's necessary to pass them as a list? We can't apply multiple boundary handlers at the same time

**Comment by ljvmiranda921** [comment]
> I like it! smile Let's do something like that.

Yes maybe we can work on the same PR branch? There's also the need to use handlers for Velocity (check your link in Gitter). Maybe we can split the work between us?

**Comment by ljvmiranda921** [comment]
> I wonder if it might suffice to use a VelocityHandler. If the particles don't even leave the bounds there is no reason to fix the position thinking Maybe we can try it out like that?

I think the two handlers solve different problems. Our perspective now should shift from "how to prevent particles from going out-of-bounds" into "what happens when they're out of bounds?" 
The `BoundaryHandler` dictates what happens whenever we go out-of bounds, "reflective" does this nifty trick, "resample" does another, etc. Of course, after changing the position, we also have to deal with the velocity that caused this potential-out-of-bounds, that's when `VelocityHandler` comes in. 

I think having the two improves particle exploration, making them less likely to be stuck in a local minima.

**Comment by whzup** [comment]
Ok :+1: Let's do this one!
