### ISSUE TITLE
discrete missing param init_pos

### ISSUE THREAD

**Issue by dfhljf** [ljvmiranda921/pyswarms#248]
**Describe the bug**
if discrete:
        position = generate_discrete_swarm(
            n_particles, dimensions, binary=binary
        )
\# position = generate_discrete_swarm(
\#            n_particles, dimensions, binary=binary,init_pos=init_pos
\#        )
    else:
        position = generate_swarm(
            n_particles,
            dimensions,
            bounds=bounds,
            center=center,
            init_pos=init_pos,
        )

**Comment by ljvmiranda921** [comment]
Hi @dfhljf , understood. so we need to specity init_pos in `create_swarm` right?
That should be easy, but we need some validators so that init_pos is actually for discrete or for binary. We'll do that for the next release. 

But are you interested to make a PR for this?
