### ISSUE TITLE
Ring topology update velocity basing on gbest instead of lbest.

### ISSUE THREAD

**Issue by Kevin9436** [ljvmiranda921/pyswarms#250]
**Describe the bug**
In backend.topology.ring module, the compute_gbest() method has already calculate the best_neighbor, but in the compute_velocity() method it call operators.compute_velocity(), which uses gbest for updating.

**Expected behavior**
Pass the best_neighbor to the ring.comput_velocity() method and calculate the social part with it. 

**Additional context**
The lbest algorithm is mentioned by you in issue[#170](https://github.com/ljvmiranda921/pyswarms/issues/170)
Reference: A. Engelbrecht, Computational Intelligence 2nd Ed. p290,292,293

@whzup

**Comment by whzup** [comment]
Welcome, @Kevin9436! Thank you for reporting this bug!

Excuse me, though, as I don't fully understand your point here 😞. So you say we should pass the `best_neighbor` to the `compute_velocity()` method and calculate the social part with it. We actually already do that but with a bit of a detour to the `LocalBestPSO`/`GeneralOptimizerPSO`:
We store the `best_neighbor` in the swarm (using the `swarm.best_pos` attribute) in [this line](https://github.com/ljvmiranda921/pyswarms/blob/master/pyswarms/single/local_best.py#L218) and then use it in the `compute_velocity()` method [here](https://github.com/ljvmiranda921/pyswarms/blob/master/pyswarms/backend/operators.py#L123). If this isn't what you reported please correct me!

**Comment by Kevin9436** [comment]
My confusion is about [this line](https://github.com/ljvmiranda921/pyswarms/blob/b83e99be17d3b05a5948b73ad11fd2a0f6b0ce36/pyswarms/backend/topology/ring.py#L83). If my prehension is not wrong, this `best_pos` is the global best of the whole swarm and this line is to pick the minimum cost position from all best neighbour. 

Since the neighbour size of each particle is `k`, for local best algorithm, the particle can only know the best position of the nearest `k` particles, while you give the global best position to it.

I think the right way to do this is to return a new parameter `local_best = swarm.pbest_pos[best_neighbor]` and replace the `best_pos` [here](https://github.com/ljvmiranda921/pyswarms/blob/b83e99be17d3b05a5948b73ad11fd2a0f6b0ce36/pyswarms/backend/operators.py#L123) with it.

**Comment by whzup** [comment]
@Kevin9436, ok I see your point now, thanks for the further explanation 👍. I'll have a look at it as soon as I can spare some time. I'm kind of busy though as the semester has just started so it might take some time until I can get behind this 😞.
Thanks for reporting! 😃:100:

**Comment by Kevin9436** [comment]
@whzup ok, no problem. I'll go on studying your code. Honestly, your guys project really helps me a lot on comprehending the PSO algorithm. Good luck  on your new semester! :)

**Comment by whzup** [comment]
Thanks a lot! :heart: I'm glad you appreciate this project :smile: 

I noticed that this bug does is present in all the topologies. Gotta rewrite the whole tests :confounded:

**Comment by cklat** [comment]
Can anyone of you guys explain to a PSO newbie how this bug affects the usage of pyswarms? To me it seems that it is a major bug in the sense that for other settings than global neighbours all the calculations will be wrong, is this correct? Can I still use the package? I just bumped into pyswarms since I have to implement the PSO algorithm for a project and thought I could maybe save some time using the pyswarms library.

Thanks a lot for your help!

**Comment by ljvmiranda921** [comment]
Hi @cklat , the standard Global Best PSO should work as expected. We're sorry if this Issue has been stale for long, most of the maintainers are either busy at their day-jobs or in school. Other topologies should converge and find an optima, but its exploration aspect will be affected.

**Comment by ljvmiranda921** [comment]
@stalebot cancel
