### ISSUE TITLE
Using pyswarms for symbolic regression?

### ISSUE THREAD

**Issue by RabbitJackTrade** [ljvmiranda921/pyswarms#254]
This is more a question that a feature request; coming from a newbie:

Having gone through the [Training a Neural Network notebook](https://github.com/ljvmiranda921/pyswarms/blob/master/examples/train_neural_network.ipynb), I was wondering if it's possible, and if so, how one would go about, using pyswarms to solve a symbolic regression problem [like this one, for example](https://gplearn.readthedocs.io/en/stable/examples.html).

Thanks.

**Comment by whzup** [comment]
Hello @RabbitJackTrade and welcome to PySwarms! :smile: 

Thanks for you question. As I'm not very familiar with the topic I can't answer your question but the maintainer @ljvmiranda921 is well versed in this topic. Unfortunately, he is not online until around mid-october :disappointed: I hope your question can wait until then.

**Comment by ljvmiranda921** [comment]
Hi @RabbitJackTrade ! 

As of now, I don't think pyswarms can support symbolic regression. We'd love to, but to be honest I'm not well-versed with this topic as well. We can definitely add this to the next few features that we can implement!
