### ISSUE TITLE
 What is the Objective function in feature selection using PSO?. How do we define our objective function for feature selection? Can we use the same objective function given in the example for all feature selection problems 

### ISSUE THREAD

**Issue by Anesh117** [ljvmiranda921/pyswarms#260]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Linux]
 - Version [e.g. Ubuntu 16.04]
 - PySwarms Version [e.g. v.0.2.0]
 - Python Version [e.g. 3.6.X]

**Additional context**

**Comment by ljvmiranda921** [comment]
Hi @Anesh117 ,

### What is the Objective function in feature selection using PSO?
Right now, the objective function for feature selection using PSO is the classifier accuracy/performance. This goes with the assumption that **more relevant features leads to better classifier performance**.

### How do we define our objective function for feature selection?
It really depends on the assumptions you'll make. In terms of code implementation, simply check the examples we had in the documentation.

### Can we use the same objective function?
Sure, but if you can define a much better training objective, the better

**Comment by ljvmiranda921** [comment]
Hi @Anesh117 

Hmmm, it really depends on the dataset and the algorithm you are using. It's not guaranteed that training a neural network with PSO can solve image problems, it requires more experimentation, etc. I'd be glad if you've already figured this one out! If that's the case, would you mind sharing a Jupyter notebook of your experiments?
