### ISSUE TITLE
Update README documentation

### ISSUE THREAD

**Issue by ljvmiranda921** [ljvmiranda921/pyswarms#287]
There's so much API change that even the documentation in the README will not work right away. Any help here would really be appreciated. The goal is to just try out the code samples in the docs, and correct them into our new version.

**Comment by ndngo** [comment]
Hello @ljvmiranda921, I'd like to help out with PySwarms and claim this issue.

**Comment by ljvmiranda921** [comment]
Ok thank you @ndngo ! Please do!

**Comment by habeckmatt** [comment]
Hi @ljvmiranda921 I would like to help with this issue.

**Comment by ljvmiranda921** [comment]
Hi @habeckmatt , unfortunately this has already been taken. Perhaps you can prod around our documentation and check for inconsistencies regarding the actual API and the one documented? We would really appreciate that!

**Comment by ndngo** [comment]
Hello @ljvmiranda921, I tried out the code samples in the README. In the code sample for the sphere function optimization, I got a type error:
`TypeError: sphere() got an unexpected keyword argument 'verbose'`
when trying to run [this line of code](https://github.com/ljvmiranda921/pyswarms/blob/574519aa21b4092810998fe89fed2d8f65c00618/pyswarms/single/global_best.py#L183)

The Hyperparameters search tools code samples executed successfully.

When attempting to run the Swarm visualization code samples, it could not find the tkinter module when importing the plotting modules:
`ModuleNotFoundError: No module named 'tkinter'`

**Comment by ljvmiranda921** [comment]
Hi @ndngo , would you like to make a PR so that the README is updated to make everything work?

**Comment by ndngo** [comment]
@ljvmiranda921 Sure!

**Comment by ndngo** [comment]
Hi @ljvmiranda921, I've gotten the code to compile but I'm having trouble getting plt.show() to display the graphs. I tried changing the backend matplotlib uses from Agg to GtkAgg with no success so I was wondering how it is supposed to be set up.

**Comment by ljvmiranda921** [comment]
Hey @ndngo , what is the error message showing?

**Comment by ndngo** [comment]
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

**Comment by ljvmiranda921** [comment]
Hi @ndngo , 

Would this work? What is your OS?

```
sudo apt-get install tk-dev libpng-dev libffi-dev dvipng texlive-latex-base
```

**Comment by ndngo** [comment]
I'm using Windows Subsystem for Linux.

**Comment by ljvmiranda921** [comment]
Can you try the command above? It seems that you don't have TKinter in your system

**Comment by ndngo** [comment]
I ran the command but it still gives the same error. It doesn't seem to know that TKinter is installed.

**Comment by ndngo** [comment]
I'll try compiling matplotlib from source as this person has suggested.
https://stackoverflow.com/questions/12933335/tkagg-backend-problems?rq=1

**Comment by ndngo** [comment]
I saved the graphs as pngs instead of trying to display them in a new window to test the output. 
![test](https://user-images.githubusercontent.com/16291290/52973711-f7f55800-338c-11e9-9498-8aebcd33f420.png)
![test1](https://user-images.githubusercontent.com/16291290/52973712-f7f55800-338c-11e9-8a44-a38b902c3a40.png)
![test2](https://user-images.githubusercontent.com/16291290/52973713-f7f55800-338c-11e9-9924-903e2e9381d6.png)

Is this good?
