### ISSUE TITLE
NOTICE: Documentations Maintainer Wanted

### ISSUE THREAD

**Issue by ljvmiranda921** [ljvmiranda921/pyswarms#291]
After a few API changes for the last few releases, we realized that there are still some inconsistencies in our API Documentation, Tutorials, and Examples with what the actual library is. We would love to welcome a new Maintainer who will be in-charge for that. 

**We would appreciate someone who:**
- Is familiar wit the Git workflow (push/pull, branching, etc.)
- Has some design skills (we might probably change our logo, and this project maybe a good way for practicing)
- Welcoming and warm especially to Github newbies and first-time contributors
- Great initiative (just dive-in and do some PRs!)

**Responsibilities include:**
- Facilitating Issues/PRs concerning documentation 
- Opening up documentation PRs/fixes
- Actively spotting for docs inconsistencies (API Documentation, Tutorials, Jupyter Notebook Examples)

**Short-term goal:**
- Release a version with all aspects of documentation ironed and cleaned-out

As you all know, PySwarms is an open-source project and does not generate money whatsoever. To be honest, we don't have anything to offer you aside from a project where you can spend your time with. You don't need to stay forever (2-3 month commitment) and this is not a lifetime thing. This is purely volunteer-driven.

This library is being used by research labs, in classrooms, practitioners, etc., and I think having a good up-to-date documentation is crucial for those that depend on us. 

If you're interested, please contact us!
cc: @whzup @SioKCronin

**Comment by stevenbw** [comment]
@ljvmiranda921 I'm keen to help out with this :)

**Comment by ljvmiranda921** [comment]
Hey @stevenbw ! Awesome! Will get back to you on Monday!
