### ISSUE TITLE
BinaryPSO returns swarm positions instead of best particle position

### ISSUE THREAD

**Issue by danielcorreia96** [ljvmiranda921/pyswarms#292]
**Describe the bug**
The binary optimizer returns the entire final swarm instead of the final best position.

I think this happens because in the return stage of the optimize() function, we are copying self.swarm.best_pos which is an array (n_dimensions, particles), instead of the position of the best particle. 

The expected behavior is implemented in local_best.py.

Hence, I think
`final_best_pos = self.swarm.best_pos.copy() `
should be
`final_best_pos = self.swarm.position[self.swarm.pbest_cost.argmin(axis=0)].copy()`

**To Reproduce**
Run the feature_subset_selection.ipynb notebook.

**Additional context**
Screenshots using example notebook (best position differs due to separate executions)
Current Behavior
![pyswarms_binary_before_fix](https://user-images.githubusercontent.com/17486065/52802338-a771b800-3077-11e9-895a-bcf94aa1baba.PNG)
Expected Behavior (with a quick fix)
![pyswarms_binary_after_fix](https://user-images.githubusercontent.com/17486065/52802343-a9d41200-3077-11e9-96ff-aede47ede9cf.PNG)

**Comment by danielcorreia96** [comment]
FYI, I re-tested with previous versions and this behaviour only appeared at 0.4.0 and I'm pretty sure it was introduced during the commit for fixes in topologies -> https://github.com/ljvmiranda921/pyswarms/commit/d226c35c1d8425b1bf70b7f913d6144bc60eddd1

Notice that local_best.py was updated but binary.py wasn't 🔍

**Comment by ljvmiranda921** [comment]
Hi @danielcorreia96 , 

Thanks for this Issue. So this bug is currently active at the current version, right? Would you like to submit a Pull Request for this?

**Comment by danielcorreia96** [comment]
@ljvmiranda921 
1. Yes, this bug is active in the current version (1.0.1).
2. I can make the PR with this fix. I just wanted to check first if the problem was in the optimizer or in the Ring topology (seems to be the common factor here) 👍
