### ISSUE TITLE
DOC: Documentation guidelines

### ISSUE THREAD

**Issue by stevenbw** [ljvmiranda921/pyswarms#294]
Writing documentation including docstrings and examples is an ongoing task. I believe there should be some (initially rough) guidelines in place to allow new and existing contributors to follow a consistent standard and formatting of documentation.

I think it would be good to get other people's thoughts on this before diving straight in. Some discussion points could be:

- Are guidelines necessary?
- What aspects of documentation should guidelines exist for? For example docstrings, example notebooks.
- Should we adhere to an already existing guideline structure? For example the Numpy Docstring Standard. We could also follow some variation of this.

Please comment if you have any thoughts.
cc: @ljvmiranda921 @whzup

**Comment by ljvmiranda921** [comment]
Hi @stevenbw , these are awesome questions. Let me answer in a while

**Comment by ljvmiranda921** [comment]
Hi @stevenbw ,

Again, welcome to PySwarms! Thank you so much for volunteering!

- Yes guidelines are absolutely necessary! This may involve the current writing style (method docstrings should be in imperative form, git commits should also have a certain commit message, etc. etc.)
- I think docstrings and example notebooks should have good guidelines at best
- Right now we adhere to the numpy docstring structure. It works well with Sphinx and is readable even by just looking at the source-code

Right now the urgent tasks would be:
- Finishing up #287 and #264 : There were some people who said they'll contribute, but only one of them has opened a Pull Request.
- Sync the example notebooks in our [online documentation](https://pyswarms.readthedocs.io/en/latest/examples/usecases.html)

Nice-to-haves would be:
- Using [doctest](https://docs.python.org/2/library/doctest.html) to check if our code samples in the docs are correct.
- [Using ipython in documentation](https://github.com/ljvmiranda921/pyswarms/issues/107)

The goal for now is to have an up-to-date documentation with respect to our current API (general upkeep). Inasmuch as I'd love to have a lot of contributors working on this, it would be nice if someone is focused in accomplishing these tasks.

**Comment by stevenbw** [comment]
Hi @ljvmiranda921 no problem I am happy to help :)

Thanks for the ideas - maybe a little later I will put some brief ideas on guidelines into the contributing guide.

I'll start working through some of the points you mentioned above I imagine some of it will be self assigned but I will create issues anyway.

**Comment by ljvmiranda921** [comment]
Thank you as well! This is much appreciated! 
If you have any questions or anything don't hesitate to ping us!
I also added you to the collaborator's list. You should receive an invite by now

**Comment by ljvmiranda921** [comment]
Closing this issue. Thank you @stevenbw for joining us!
