### ISSUE TITLE
DOC: Sync example notebooks

### ISSUE THREAD

**Issue by stevenbw** [ljvmiranda921/pyswarms#297]
Due to some API changes, there was a need to update some example notebooks (see #264). These changes now need to be synced with the [online documentation][doc link].

[doc link]: https://pyswarms.readthedocs.io/en/latest/examples/usecases.html

Status of notebooks:
- [x] basic_optimization.ipynb
- [x] custom_optimization_loop.ipynb
- [x] electric_circuit_problem.ipynb (new)
- [ ] feature_subset_selection.ipynb (assigned to @gustavovelascoh )
- [ ] inverse_kinematics.ipynb
- [ ] optimization_loop.ipynb
- [ ] train_neural_network.ipynb
- [ ] visualization.ipynb

Status of documentation:
- [x] basic_optimization.rst
- [ ] custom_objective_function.rst
- [x] custom_optimization_loop.rst
- [ ] electric_circuit_problem.rst (to be added?)
- [ ] feature_subset_selection.rst
- [ ] inverse_kinematics.rst
- [ ] visualization.rst

**Comment by citomcclure** [comment]
Hi @stevenbw ! 

I'll take this one if that's okay! I will follow a lot of the direction given in the referenced issue (#264).

**Comment by stevenbw** [comment]
Hi @citomcclure that's great to hear!
Don't hesitate to ask if you need any support with regards to the issue.

**Comment by citomcclure** [comment]
Hi @stevenbw 

I forked the repo, and then cloned both my fork and the upstream. I made a new branch "issue-297" on my fork. I was able to access the notebooks, but I did not see anything else besides the notebooks in `pyswarms/examples`.

I assume I am suppose to update the `usecases.rst` file seen here: https://github.com/ljvmiranda921/pyswarms/tree/master/docs/examples

Any help would be great! Thanks.

**Comment by citomcclure** [comment]
Oh. Well now I see that the docs are in `docs/examples`. I'm good for now then!

**Comment by citomcclure** [comment]
Hi @stevenbw !

A couple of questions so far:

- I can only update the `custom_optimization_loop.ipynb` so far right? I looked through the recent commits and saw that was the only one updated. So, do I do that one, make a pull request, and then wait for the others?
- I was manually going through and updating changes, but I found a library, `nbconvert`, that can convert to `.rst` files. That should be okay right?


Thanks!

**Comment by stevenbw** [comment]
Hi @citomcclure !

Yes - I am trying to find out if the others are in progress or not. As you suggested, I think it would be a good idea to submit the PR for the one file and then wait for the others.

I have not used that library myself but it should be okay. I would suggest reading through before you submit a PR, just to make sure the library hasn't done anything obviously wrong.

**Comment by citomcclure** [comment]
Hey @stevenbw  , do I have to do virtualenv tests for documentation changes before making a pull request?

**Comment by ljvmiranda921** [comment]
Hello @stevenbw , would it be nice to have a checklist on the very first comment just to track how much of our example notebooks and its corresponding examples in the documentation were already done? Something like this:

- [ ] basic_optimization.ipynb (assigned to @ljvmiranda921 ) 
- [ ] basic_optimization.rst (assigned to @ljvmiranda921 )

**Comment by stevenbw** [comment]
Hi @ljvmiranda921 , I have added a checklist to the first comment. I will update it as the notebooks and documentation are updated.

**Comment by ljvmiranda921** [comment]
Awesome! Thanks a lot @stevenbw !

**Comment by ljvmiranda921** [comment]
Stalebot keep

**Comment by ljvmiranda921** [comment]
Closing this issue.
