### ISSUE TITLE
Optimizers have a "fast" flag that defaults to False

### ISSUE THREAD

**Issue by danielcorreia96** [ljvmiranda921/pyswarms#303]
**Describe the bug**
I was looking at the BinaryPSO code and I noticed this:
https://github.com/ljvmiranda921/pyswarms/blob/843ceba2aee56bae39f987d7f328db193ebb8e2a/pyswarms/discrete/binary.py#L170-L172

which refers to an optional argument `fast` passed to the `optimize` method:
https://github.com/ljvmiranda921/pyswarms/blob/843ceba2aee56bae39f987d7f328db193ebb8e2a/pyswarms/discrete/binary.py#L150-L151

This felt weird to me because I don't see a use case where we would need/want to slow down the execution of the optimizers (maybe for visualization but that's already post-optimization... 🤔).

So, I guess my questions are:
- Why was this `fast` parameter introduced?
- Should it really default to False?

**Additional context**
This "fast" argument came in during the reporter/logging refactorings (see https://github.com/ljvmiranda921/pyswarms/commit/57b8dcd80b63435aa84bce7f1950f71501128718)

Also you can find additional usages in the remaining optimizers (see this search https://github.com/ljvmiranda921/pyswarms/search?q=%22fast%3DFalse%22&unscoped_q=%22fast%3DFalse%22)

**Comment by ljvmiranda921** [comment]
Hi @danielcorreia96 , 

To be honest that was a wrong design decision of mine just so that the progress bars from `tqdm` would look nice. That's an invalid tradeoff, I admit. In hindsight we should remove that non-feature.

**Comment by danielcorreia96** [comment]
Hi @ljvmiranda921,

I figured it was something like that to "see" `tqdm` doing things 😅.

I'll make a fixing PR for this soon: should be pretty straightfoward 👍

**Comment by ljvmiranda921** [comment]
You can make a PR! I just assigned it to myself for accountability haha
