### ISSUE TITLE
Relax dependency requirements

### ISSUE THREAD

**Issue by brandondube** [ljvmiranda921/pyswarms#323]
Pyswarms does not explicitly depend on the state of (for example) scipy@1.2.0.  It would be nice to see the requirements changed to be (for example) scipy > 1.2, if it depends on features introduced then.

It would also be nice to see this folded into setup.cfg in keeping with the best practices for modern setuptools/distutils.

Would a PR making these changes be welcome?  If so, are there any fancy new features of numpy/scipy/etc that pyswarms uses that enforce a minimum version number?

**Comment by ljvmiranda921** [comment]
Hi @brandondube , 

We'd want to pin the `requirements.txt` and `requirements-dev.txt` file as much as possible so that everything is reproducible. If you are to use PySwarms into your system, I'd recommend installing it inside a virtual environment so that it avoids clashing with any dependencies you currently have system-wide. 

Are you encountering any problems with the dependencies? Maybe we can fix that one out.

**Comment by brandondube** [comment]
Why such a strong goal of reproducibility?  This is a library, not an app.  Compatibility is arguably (and IMO) more important.  Save reproducibility for CI with a travis.yml configuration that has pinned versions or something.

The pinned versions are an annoyance more than a problem -- I installed pyswarms and it clobbered a good chunk of my venv's (superior) versions with its own, arbitrary requirements.  Most of these are from conda/conda-forge and then become pip versions which is not very nice.

pyyaml is missing from the dependencies, too.

**Comment by ljvmiranda921** [comment]
Hello,

As a scientific tool, we'd want our tools to be as controlled as possible. I'd still maintain that we pin our dependencies. It's also my guarantee, as a maintainer, that whatever I ship will always work. Hmm, it's definitely my first time to encounter a dependency problem in this library.

Normally I'd set things up like this:

```
$ virtualenv venv # create venv
$ pip install pyswarms # or do the pip install -r requirements.txt when you cloned it
```

I wonder how it clobbers your virtual environment. Any other packages you are using? 

As for pyyaml, it has been added 20+ days ago: https://github.com/ljvmiranda921/pyswarms/commit/8b4046277163b11e057beed4557de94b6a530985

Thank you!

**Comment by brandondube** [comment]
Clobbering is because *that's what pip does.* . pyswarms wants scipy@1.2.0, I have 1.2.1.  It uninstalls 1.2.1 and installs 1.2.0.

"Control" with your req.txt is really an illusion.  Your dependencies produce > 100 other packages, most of which without pinned versions.  And if you did a pip freeze > req.txt, that file might not work on a different OS.  Pip doesn't have a resolver, so you might end up with incompatible versions, too.  (Suppose I now went and did `pip install -U matplotlib` -- this is hypothetically incompatible with pyswarms, but pip won't stop me.  And if I installed my own package that depended on matplotlib@3.0.3, this would happen automatically)

A conda-env.yml file (or, indeed, producing a conda feedstock) will lock your versions and conda's resolver will take care of them for the user.  This is yet another tool like poetry or pipenv, but Conda is generally preferred for science since it brings binary distributions of packages with heterogeneous dependencies.

You really shouldn't worry about all this so much though.  Your dependencies are mostly part of the scientific stack with long release cycles, high test coverage, and far more high profile dependents than your package which will certainly cry foul if a major bug was introduced.

A good compromise that satisfies both would be to have your req.txt -- ineffectual as it is -- to allow people to install with pip install -r if they want this, but also not pin versions in setup.py.

What you've done is really quite far outside the norm... most libraries in C/++ and python don't do this.  End programs do.

**Comment by ljvmiranda921** [comment]
> pyswarms wants scipy@1.2.0, I have 1.2.1. It uninstalls 1.2.1 and installs 1.2.0.

Sure, this won't really matter if you are inside a virtual environment because it's separate from your system-wide dependencies. Have you tried the recommendation above?

> A good compromise that satisfies both would be to have your req.txt -- ineffectual as it is -- to allow people to install with pip install -r if they want this, but also not pin versions in setup.py.

Seems possible. Thanks for the recommendation!

**Comment by ljvmiranda921** [comment]
A good resolution would be to maintain `requirements.txt` + `requirements-dev.txt` and use `requirements.in` (a relaxed version) for `setup.py`. 

I'm also going to call you out for being rude in your manner of tone. It's fine to be annoyed if things don't install properly that way you're used to, but you gonna temper your words dude. We're all volunteers just using our free time to build tools for others. 

Nice chatting with you! The maintainers will take it from here :+1:

**Comment by brandondube** [comment]
Don't tone police your users.
