### ISSUE TITLE
Binary PSO cost problem

### ISSUE THREAD

**Issue by ljvmiranda921** [ljvmiranda921/pyswarms#33]
* PySwarms version: 0.1.6a

### Description

"The cost doesn't seem to monotonically decrease from one iteration to the next.  It seems like the cost that should be returned each iteration as the best cost is the one that is the historically best across all particles, yet on some iterations the cost seems to jump up, and the final cost when the algorithm completes isn't the minimum cost it encountered and returned in previous iterations. "

"When I reduce the inertia, the problem reduces (but it's still there).  That behavior suggests to me that the global best position is computed from only particles' current positions and not their past positions.  That way, as particles become more likely to explore, they are more likely to move into and out of good solutions.  Could that be what's going on?  That the global / social best positions are computed only on the current iteration and not on the history of found solutions?"

### What I Did

```python
import numpy as np
import pyswarms as ps
from sklearn.datasets import make_regression
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X, y = make_regression(n_samples=100, n_features=300, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

# Define cost function
line_model = LinearRegression()
def rmse_particle(pos):
    line_model.fit(X_train[:,pos==1], y_train)
    pred = line_model.predict(X_test[:,pos==1])
    return np.sqrt(mean_squared_error(pred, y_test)) 

def rmse_func(positions):
    n_particles = positions.shape[0]
    j = [rmse_particle(positions[i]) for i in range(n_particles)]
    return np.array(j)

# Perform optimization
options = {'c1': 0.5, 'c2': 0.5, 'w':0, 'k':30 , 'p':2}
optimizer = ps.discrete.BinaryPSO(n_particles=30, dimensions=300, options=options)
optimizer.reset() 
cost, pos = optimizer.optimize(rmse_func, print_step=1, iters=300, verbose=2)
```

**Comment by ljvmiranda921** [comment]
Possible culprit is self assigning personal best PSO without keeping a history of positions and cost. 
See the relevant code [here].(https://github.com/ljvmiranda921/pyswarms/blob/master/pyswarms/discrete/binary.py#L165:L200)

**Comment by CPapadim** [comment]
I submitted a pull request for review to fix this issue here:  https://github.com/ljvmiranda921/pyswarms/pull/34
