### ISSUE TITLE
help me in my ORgate

### ISSUE THREAD

**Issue by AlOo2002** [ljvmiranda921/pyswarms#337]
hi everyone 
im new in coding and im trying to do OR gate by using neural network but it seems there is something wrong can any one help me
her is my code

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
# Import PySwarms
import pyswarms as ps
%load_ext autoreload
%autoreload 2

X = np.array([[1,1],
              [0,1],
              [1,0], 
              [0,0]])
y= np.array([1,1,0,0])

def forward_prop(params):
    n_inputs = 2
    n_hidden = 3
    n_classes = 1
    
    # Roll-back the weights and biases
    W1 = params[0:6].reshape((n_inputs,n_hidden))
    b1 = params[6:9].reshape((n_hidden,))
    W2 = params[9:12].reshape((n_hidden,n_classes))
    b2 = params[12:13].reshape((n_classes,))
    
    # Perform forward propagation
    z1 = X.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2
    
    # Compute for the softmax of the logits
    exp_scores = np.exp(logits)
    probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True) 
    
    # Compute for the negative log likelihood
    N = 4 # Number of samples
    corect_logprobs = -np.log(probs[range(N), y])
    loss = np.sum(corect_logprobs) / N
    
    return loss

def f(x):
    n_particles = x.shape[0]
    j= [forward_prop(x[i]) for i in range(n_particles)]
    return np.array(j)

%%time
# Initialize swarm
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}

# Call instance of PSO
dimensions = (2*3) + (3*1) + 3 + 1 
optimizer = ps.single.GlobalBestPSO(n_particles=100, dimensions=dimensions, options=options)
# Perform optimization
cost, pos = optimizer.optimize(f, iters=1000)

IndexError: index 1 is out of bounds for axis 1 with size 1
thanx

**Comment by ljvmiranda921** [comment]
Hi, @AlOo2002 can you copy paste the whole error message here (the full traceback not just the `IndexError` message) so that I can diagnose the problem further :)

**Comment by AlOo2002** [comment]
@ljvmiranda921 thank you very much sir for replying back  I appreciate that .
and this is whole error message :
IndexError                                Traceback (most recent call last)
<timed exec> in <module>

~\Anaconda3\lib\site-packages\pyswarms\single\global_best.py in optimize(self, objective_func, iters, fast, **kwargs)
    181             # Compute cost for current position and personal best
    182             # fmt: off
--> 183             self.swarm.current_cost = objective_func(self.swarm.position, **kwargs)
    184             self.swarm.pbest_pos, self.swarm.pbest_cost = compute_pbest(self.swarm)
    185             # Set best_cost_yet_found for ftol

<ipython-input-5-a0ab2300fdaf> in f(X)
      1 def f(X):
      2     n_particles = 4
----> 3     j= [forward_prop(X[i]) for i in range(n_particles)]
      4     return np.array(j)

<ipython-input-5-a0ab2300fdaf> in <listcomp>(.0)
      1 def f(X):
      2     n_particles = 4
----> 3     j= [forward_prop(X[i]) for i in range(n_particles)]
      4     return np.array(j)

<ipython-input-4-7d49f6b19a2d> in forward_prop(params)
     22     # Compute for the negative log likelihood
     23     N = 4 # Number of samples
---> 24     corect_logprobs = -np.log(probs[range(N), y])
     25     loss = np.sum(corect_logprobs) / N
     26 

IndexError: index 1 is out of bounds for axis 1 with size 1

thank you again

**Comment by AlOo2002** [comment]
@ljvmiranda921  than you sir very much for your time i solved the problem

**Comment by ljvmiranda921** [comment]
Oh ok! Would you mind sharing us the solution? @AlOo2002

**Comment by AlOo2002** [comment]
İ just changed the n-classes number to 2 
But ım not sure if my code explane the gate system for OR AND gates 🙈 what do you think sir 🙈

**Comment by ljvmiranda921** [comment]
I think the OR gate should have the following inputs:

```
X1 X2 Y
1    1   1
0    1   1
1    0   1
0    0   0
```

```
X = np.array([[1,1],
[0,1],
[1,0],
[0,0]])

y= np.array([1,1,1,0])   # instead of y= np.array([1,1,0,0])
```

If the optimization goes well then it should work!

**Comment by AlOo2002** [comment]
Yaaa 🙊 it worked you are great 💪🏼 Thanx alot for every thing 🌸

**Comment by ljvmiranda921** [comment]
Glad to be of help!
