### ISSUE TITLE
Is it possible to only get the integer numbers?

### ISSUE THREAD

**Issue by tsehso** [ljvmiranda921/pyswarms#338]
* PySwarms version: 1.0.2
* Python version: 3.6
* Operating System: Mac

### Description

Hi there, 

I recently just finished my first optimization using pyswarms and found that all the results I got were floating numbers.

Since the later on manufacturing process doesn't have such high accuracy, the result of the final product will have a very large difference with my optimization result.

I'm thinking is it possible to only get the integer numbers or to restrict the floating numbers to only third decimal place?

**Comment by ljvmiranda921** [comment]
Hi @tsehso , have you already solved this problem? Would you mind sharing the solution?

**Comment by tsehso** [comment]
Hi @ljvmiranda921,  I haven't solved this problem yet since I am confused about whether this problem came from the module I used or from the PSO. I'm still working on it and if there is any update about this problem, I will share it

**Comment by whzup** [comment]
@tsehso Please see #400
