### ISSUE TITLE
How do Optimize 4 Parameter

### ISSUE THREAD

**Issue by MohMehrnia** [ljvmiranda921/pyswarms#339]
HI
How do optimize 4 parameter with fitness f(x) = a+b+c+d+e
and 
a,b,c,d,e is a range

**Comment by ljvmiranda921** [comment]
Hi @MohMehrnia , I was wondering what are the things you've already tried out so far? In your objective function, `f(x)`, how is the equation dependent on `x`?

**Comment by MohMehrnia** [comment]
Hi, it is a sample
How can optimize funtion with 4 patameter
