### ISSUE TITLE
Verbose option is missing (it is in documents)

### ISSUE THREAD

**Issue by msat59** [ljvmiranda921/pyswarms#340]
Hi.

Please bring back the verbose option. I need to disable progress bar. I can disable it in the code; but it's better to have it as an option.

According to the documents, optimize should have the option; but both **verbose** and **print_step** have been removed.

`optimizer.optimize(f, print_step=100, iters=1000, verbose=2)`

Thanks.

**Comment by ljvmiranda921** [comment]
Yup, we’re fixing the docs now. Sorry for the confusion!

**Comment by msat59** [comment]
Any plan to add it to the code? I've already added it to the local version.

```
if not verbose:
                self.rep.hook(best_cost=self.swarm.best_cost)
```

**Comment by ljvmiranda921** [comment]
As of now we’re planning to add it in the code, but I might release the new version this weekend. For now please use your local changes and maybe open up a PR. Sorry I haven’t been on top of Issues, work got reallyy busyy

**Comment by ljvmiranda921** [comment]
Hi documentation is now updated! Will be closing this issue now :+1:

**Comment by devkicks** [comment]
> Any plan to add it to the code? I've already added it to the local version.
> 
> ```
> if not verbose:
>                 self.rep.hook(best_cost=self.swarm.best_cost)
> ```

Where are you making these changes? I also need to turn off verbose option as it is constantly printing messages I dont want to see. To me this is quite essential option to have.

**Comment by ljvmiranda921** [comment]
Hi @devkicks , we haven't added it up in the codebase and just updated the documentation. Would you be able to help out in creating a PR for this?

**Comment by whzup** [comment]
@ljvmiranda921 I think we can easily implement this feature, though. We just add a `verbose` argument to the `optimize` method and then choose the iterator of the loop (because this generates the progress bar) and the local logging level. Do you think this works?

**Comment by ljvmiranda921** [comment]
^Hi @whzup sorry I wasn't able to reply properly, ok I think that works!

**Comment by nishnash54** [comment]
Adding the `full` verbose option would be great when running optimizations with fewer iterations. For a large number of iterations, the `print_step` parameter makes a lot of sense. 
Currently you are using a logger for the results. May I suggest you have something like a tabular format that makes it easier to read, maybe something like `gplearn`. [Here's](https://github.com/trevorstephens/gplearn/blob/master/doc/gp_examples.ipynb) an example of the verbose.

**Comment by msat59** [comment]
> > Any plan to add it to the code? I've already added it to the local version.
> > ```
> > if not verbose:
> >                 self.rep.hook(best_cost=self.swarm.best_cost)
> > ```
> 
> Where are you making these changes? I also need to turn off verbose option as it is constantly printing messages I dont want to see. To me this is quite essential option to have.

There are three places:

pyswarms\single\global_best.py
pyswarms\single\general_optimizer.py
pyswarms\discrete\binary.py

search for **self.rep.hook(best_cost=self.swarm.best_cost)** and add that condition. In addition, you should add verbose=False in function declaration. I can change the code if it's required.

**Comment by ljvmiranda921** [comment]
Hi @msat59 @nishnash54  sorry I don't have the bandwidth to do new updates. If you can open a PR on this that would be great! Let's do @msat59 's version first, then maybe work on @nishnash54 's suggestion.

**Comment by msat59** [comment]
> Hi @msat59 @nishnash54 sorry I don't have the bandwidth to do new updates. If you can open a PR on this that would be great! Let's do @msat59 's version first, then maybe work on @nishnash54 's suggestion.

I rechecked my fix now, after a year. It's not completely verbose. I will check it tomorrow morning.

**Comment by msat59** [comment]
I finally fixed the verbosity; but I don't know if can contribute to the code change or I should paste the modified code here
