### ISSUE TITLE
Mutation in PSO

### ISSUE THREAD

**Issue by BalasubramanyamEvani** [ljvmiranda921/pyswarms#341]
**Is your feature request related to a problem? Please describe.**
Hi ! 

I have been testing PSO for my research work, and came across the problem that PSO falls in the local minima if the particles gets attracted towards the best particle very quickly.

**Describe the solution you'd like**

Hence, i would like to add an option for mutation (like in GA). Gaussian, Cauchy are some that seemed to working.  I have been using pywarms recently for my work and it is a great package, I was wondering about the viability of my request, any comments would be appreciated, also if it seems possible, I would like to work on a PR for it with some guidance since it would be my first open source issue to work on. 

Thank you.

**Additional context**

Many papers mentions use of mutation in PSO, some of them which I read are:

https://www.sciencedirect.com/science/article/pii/S0164121212000210
https://ieeexplore.ieee.org/document/4223196

**Comment by ljvmiranda921** [comment]
Hi @BalasubramanyamEvani , sorry for the very late reply.
Mutation in PSO seems to be a pretty nice thing to add up. I'd suggest we can try it out first by adding a new optimizer, similar to `global_best` and `local_best` that involves the mutation parameter (rather than having it in the base class).

What do you think @whzup ?

**Comment by whzup** [comment]
@ljvmiranda921 Seems like a cool addition :+1:
@BalasubramanyamEvani I think it's best if you have a look at the GlobalOptimizer / LocalOptimizer / GeneralOptimizer classes [here](https://github.com/ljvmiranda921/pyswarms/tree/master/pyswarms/single) so you get a first impression on how the optimizers are constructed. Are you familiar with the git workflow? If yes just open up a PR and we discuss things further there, if not I can provide some quick start tips if you want.

**Comment by BalasubramanyamEvani** [comment]
Hi, I am very sorry for the late reply. It is my final year hence I was very busy with submission of my research project. I will go through the optimizers mentioned and yes I am new to the git workflow. So it would be great if @whzup can help me !
