### ISSUE TITLE
Mixed Integer and Continuous variables

### ISSUE THREAD

**Issue by resetscoder** [ljvmiranda921/pyswarms#342]
**Is your feature request related to a problem? Please describe.**
Hi! I am currently working on a plant Layout Optimization Problem, which is in my case a non-convex MINLP - Mixed Integer Non-Linear Programming problem. PSO could be well suited to my problem but I have to work with both integer and continuous variants. Currently PySwarms is implemented with only binary or only continuous variants.

**Describe the solution you'd like**
One of the solution in the literature is to keep the main PSO algorithm and velocity updating process, and at any iteration after finding the new position of particles, appropriate variables can be made discrete by finding the nearest discrete value to the current continuous variable.

May I interact with the swarm array for example in the opt_func ? Or should code my own PSO optimization loop ?
```
def opt_func(X):
    n_particles = X.shape[0]  # number of particles
    
    #HERE MODIFY THE SWARM ARRAY X
 
    #calculate cost
    co = [cout(X[i],CC,CH,dimensions) for i in range(n_particles)]
    return np.array(co)
```

Thank you !

**Comment by whzup** [comment]
@resetscoder Please see #400
