### ISSUE TITLE
Parallel particle evaluation is stuck

### ISSUE THREAD

**Issue by starfriend10** [ljvmiranda921/pyswarms#346]
* PySwarms version: 1.1.0
* Python version: 3.6
* Operating System: WIN10 64bit

### Description

First, thanks for developing the parallel particle evaluation function.
I was trying to use it, but the program was stuck for a long time when using the function.
Specifically, it is okay without "n_processes" (parallel particle evaluation), but it is stuck with "n_processes".

### What I Did

**Part of the code:**

```
np.random.seed(300)  # for reproducibility

def func(x):
##Model details are not shown here... a customized machine learning function 
    return MAPE_tr


def f(x):
    n_particles = x.shape[0]
    j = [func(x[i]) for i in range(n_particles)]
    return np.array(j)
    
from pyswarms.single.global_best import GlobalBestPSO
    
bounds = (np.array([0.01, 0.01]), np.array([0.5, 0.5]))
options = {'c1': 0.5, 'c2': 0.3, 'w': 0.9}

optimizer = GlobalBestPSO(n_particles=50, dimensions=2, options=options, bounds=bounds, ftol=0.002)

%%time
cost, pos = optimizer.optimize(f, iters=2, n_processes=2)
```
**Ouputs:**
**_without "n_processes":_**
%%time
cost, pos = optimizer.optimize(f, iters=2)
2019-05-26 22:04:08,950 - pyswarms.single.global_best - INFO - Optimize for 2 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
pyswarms.single.global_best:  50%|█████     |1/2, best_cost=12.72019-05-26 22:07:01,447 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 12.72566079067286, best pos: [0.01145804 0.47942748]
Wall time: 2min 52s

**_with "n_processes", stuck for a long time:_**
%%time
cost, pos = optimizer.optimize(f, iters=2, n_processes=2)
2019-05-26 22:08:35,978 - pyswarms.single.global_best - INFO - Optimize for 2 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}

pyswarms.single.global_best:   0%|          |0/2

**The computer can be used for parallel computation, which I did for grid search. As you see that the algorithm is also good without "n_processes". Did I miss something simple? Thank you.**

**Comment by ljvmiranda921** [comment]
Oh no, this seems to be a critical bug. I'm sorry about that. You think you can carry this over? @whzup @danielcorreia96 ?

**Comment by whzup** [comment]
@ljvmiranda921 I'll have a look at it :+1:

**Comment by starfriend10** [comment]
**Some additional tests/info:**

- Tested a simple, built-in function, _rastrigin_; works well (although parallel is slower than non-parallel).

- Tested a simple machine learning function, _support vector regression (SVR)_, it was also stuck.

**Code for SVR:**
```
##data preprocessing is not shown here

from sklearn.svm import SVR

if __name__ == '__main__':
    __spec__ = "ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>)"
    def func(x):
        regressor = SVR(kernel='linear', C=x[0], gamma=x[1])
        `regressor.fit(scaled_X_tr,` scaled_y_tr)
        y_pred_tr_scaled = regressor.predict(scaled_X_tr)
        y_pred_tr_scaled = y_pred_tr_scaled.reshape(-1,1)
        y_pred_tr  = scaler_rv.inverse_transform(y_pred_tr_scaled)
        MAPE_tr = mean_absolute_percentage_error(y_tr, y_pred_tr)    
        return MAPE_tr 

def f(x):
    n_particles = x.shape[0]
    j = [func(x[i]) for i in range(n_particles)]
    return np.array(j)
    
from pyswarms.single.global_best import GlobalBestPSO
    
bounds = (np.array([0.01, 0.01]), np.array([0.5, 0.5]))
options = {'c1': 0.5, 'c2': 0.3, 'w': 0.9}

optimizer = GlobalBestPSO(n_particles=50, dimensions=2, options=options, bounds=bounds, ftol=0.002)

%%time
cost, pos = optimizer.optimize(f, iters=2, n_processes=10)
```


**output for SVR-PSO:**


%%time
cost, pos = optimizer.optimize(f, iters=2, n_processes = 10)
2019-05-27 04:11:04,874 - pyswarms.single.global_best - INFO - Optimize for 2 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}


pyswarms.single.global_best:   0%|          |0/2

**Comment by whzup** [comment]
@starfriend10 Thank you for the additional information. Could you please provide the whole code you're running? I  get this error when running the code you provided:
```
NameError: name 'scaled_X_tr' is not defined
```
Regarding the rastrigin function, I think this is because of the overhead of the scheduling for multicore processing where the decision is made which core computes what. As there are only 2 iterations and a simple function this might be a significant delay.

**Comment by starfriend10** [comment]
Here is a simplified code for the example of SVR-PSO:

```import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.svm import SVR
from pyswarms.single.global_best import GlobalBestPSO


def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    MAPE = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    return MAPE

data = pd.read_excel('Sample data.xlsx')

#delete date column    
data_nd = data.drop('Date', axis =1)
data_tr = data_nd.iloc[:,:].values

obs_tr = len(data_tr.T[0])
num_var = len(data_tr.T)-1

#split x and y
X_tr = data_tr[:,:-1]
y_tr = data_tr[:,-1]
y_tr = y_tr.reshape(len(y_tr), 1)

# scale data
scaler = preprocessing.MinMaxScaler()
scaler.fit(data_tr)
scaled_data_tr = scaler.transform(data_tr)

scaler_rv = preprocessing.MinMaxScaler()
scaler_rv.fit(pd.DataFrame(data_nd.iloc[:,-1]))

# split scaled data into training and testing #
scaled_X_tr = scaled_data_tr[:,:-1]
scaled_y_tr = scaled_data_tr[:, -1]



if __name__ == '__main__':
    __spec__ = "ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>)"
    def func(x):
        regressor = SVR(kernel='linear', C=x[0], gamma=x[1])
        regressor.fit(scaled_X_tr, scaled_y_tr)
        y_pred_tr_scaled = regressor.predict(scaled_X_tr)
        y_pred_tr_scaled = y_pred_tr_scaled.reshape(-1,1)
        y_pred_tr  = scaler_rv.inverse_transform(y_pred_tr_scaled)
        MAPE_tr = mean_absolute_percentage_error(y_tr, y_pred_tr)    
        return MAPE_tr


def f(x):
    n_particles = x.shape[0]
    j = [func(x[i]) for i in range(n_particles)]
    return np.array(j)

    

bounds = (np.array([0.01, 0.01]), np.array([0.5, 0.5]))
options = {'c1': 0.5, 'c2': 0.3, 'w': 0.9}

optimizer = GlobalBestPSO(n_particles=50, dimensions=2, options=options, bounds=bounds, ftol=0.002)

cost, pos = optimizer.optimize(f, iters=2, n_processes = 10)
```


I use Spyder 3.2.8 and Python 3.6.5. Note that without "n_processes = 10", it worked well.

Please download the sample data here:
https://github.com/starfriend10/ISMLR-application/raw/master/Sample%20data.xlsx

**Comment by whzup** [comment]
Ok this seems to be an issue with Windows as it runs on Linux. @starfriend10 have you tried running the program by any other means than Jupyter?
Just for completeness, this is what I get when I run it in the Powershell:
```
RuntimeError: 
An attempt has been made to start a new process before the
current process has finished its bootstrapping phase.
This probably means that you are not using fork to start your 
child processes and you have forgotten to use the proper idiom
in the main module:
    if __name__ == '__main__':
        freeze_support()
        ... 
The "freeze_support()" line can be omitted if the program
is not going to be frozen to produce an executable.
```

**Comment by starfriend10** [comment]
> Ok this seems to be an issue with Windows as it runs on Linux. @starfriend10 have you tried running the program by any other means than Jupyter?
> Just for completeness, this is what I get when I run it in the Powershell:
> 
> ```
> RuntimeError: 
> An attempt has been made to start a new process before the
> current process has finished its bootstrapping phase.
> This probably means that you are not using fork to start your 
> child processes and you have forgotten to use the proper idiom
> in the main module:
>     if __name__ == '__main__':
>         freeze_support()
>         ... 
> The "freeze_support()" line can be omitted if the program
> is not going to be frozen to produce an executable.
> ```

I only use Spyder, so I don't know what would happen in other means.

**Comment by starfriend10** [comment]
Can I ask if there is any progress on this issue? I guess that you are all very busy, so I plan to investigate if I can use Linux to solve my problems next month.

**Comment by ljvmiranda921** [comment]
Hey @starfriend10 , sorry for not following this up. Will take a look at this next week. If possible, for the meantime, can you try running it on Linux as you mentioned? If it works then atleast we can zero-in that it is an OS problem.

Really sorry for the non-response, thank you for understanding!

**Comment by starfriend10** [comment]
@ljvmiranda921 No problem. I didn't use Python in Linux, but will give a try.

**Comment by starfriend10** [comment]
@ljvmiranda921  So I tried my codes under linux and they worked. The problem seems in the OS environment.

**Comment by ljvmiranda921** [comment]
Gotcha! Awesome! Will close this issue for now, thanks a lot @starfriend10! We'll just add a note that there's still a bug on non-nix environments
