### ISSUE TITLE
pyswarms in anaconda

### ISSUE THREAD

**Issue by carloscruzdelatorre** [ljvmiranda921/pyswarms#347]
Would it be possible to work with pyswarms under Anaconda? I have experiences errors when running Spyder and it is found no module named 'pyswarms'. pyswarms works correctly in console. Thanks in advance. regards

**Comment by ljvmiranda921** [comment]
Hi @carloscruzdelatorre , I think it is possible to install `pyswarms` inside your `conda` environment via `pip`. You can double check where the Spyder path is pointing and see if pyswarms is installed there

**Comment by ljvmiranda921** [comment]
stalebot stop

**Comment by ljvmiranda921** [comment]
stalebot stop

**Comment by ljvmiranda921** [comment]
Closing this issue. The resolution is to install pyswarms within the conda environment.

**Comment by hakonanes** [comment]
Hi @ljvmiranda921, is there still interest in releasing `pyswarms` on `conda-forge`?

We're using your package in an optimization problem in [PyEBSDIndex](https://github.com/USNavalResearchLaboratory/PyEBSDIndex), and we'd like to release it on `conda-forge`. Could I have a go? I should say that while I maintain [four packages](https://github.com/orgs/conda-forge/people?query=hakonanes) on `conda-forge`, they are all pure Python, so my experience with releasing a more complex package on `conda-forge` is non-existent.

**Comment by hakonanes** [comment]
@ljvmiranda921 and other maintainers, I've made a PR to `conda-forge` which will make PySwarms downloadable as `conda install pyswarms -c conda-forge`. I'll add you as maintainers of the pyswarms-feedstock if you ask for it.

**Comment by hakonanes** [comment]
The PR is here: https://github.com/conda-forge/staged-recipes/pull/19460. I'll wait a week (Tuesday July 5) for your response before asking for a review from the conda-forge maintainers. I can of course add you as maintainers later on if you want.

**Comment by hakonanes** [comment]
Also, the fact that the package can be downloaded from Anaconda should perhaps be added as an installation option in the docs?

**Comment by ljvmiranda921** [comment]
Hi @hakonanes , sorry for not being into this for quite some time. To answer your questions:

- Sure, let's release pyswarms on conda-forge 👍 

>  I've made a PR to conda-forge which will make PySwarms downloadable as conda install pyswarms -c conda-forge. I'll add you as maintainers of the pyswarms-feedstock if you ask for it.

Sure, I appreciate being added as a maintainer for the feedstock

> Also, the fact that the package can be downloaded from Anaconda should perhaps be added as an installation option in the docs?

Ok, I can update that installation option in the docs! 

Thanks again @hakonanes  for the help on this! 💯

**Comment by vimbainaishe18** [comment]
ImportError: cannot import name 'pso' from 'pyswarms' how do i resolve this
