### ISSUE TITLE
parallelizing pyswarms

### ISSUE THREAD

**Issue by syvlabs** [ljvmiranda921/pyswarms#350]
I think this is a super amazing library, and the main author is super great as well.

Given that swarm optimization techniques are parallelizable, how can we go about doing pyswarms in a parallel way? I think it would be **SUPER** if we can scale this to big big BIG datasets

**Comment by ljvmiranda921** [comment]
Hi sylvabs, the [latest release](https://github.com/ljvmiranda921/pyswarms/releases/tag/v.1.1.0) now offers the ability to set the number of jobs for parallel compute. All thanks to @danielcorreia96 and @whzup for pushing this feature forward! You can try it out!

**Comment by ljvmiranda921** [comment]
Closing this issue

**Comment by crcheng** [comment]
I hate **@ljvmiranda921**
