### ISSUE TITLE
n_processes option eventually throws Too Many Open Files exception

### ISSUE THREAD

**Issue by jeremysayz** [ljvmiranda921/pyswarms#351]
The n_processes option on a GlobalBestPSO optimizer seems to consume file handles. If you repeatedly create optimizers and run them (with n_processes other than None), you eventually get the Too Many Open Files exception.

The following code induces this for me with Python 3.6 with pyswarms 1.1.0:
```
import pyswarms as ps
import numpy as np

def evpeaks_multi(x):
    return(np.random.rand(x.shape[0],))  #random evaluation of each particle - irrelevant 

iters = 10             # small number of iterations to speed up example
n_particles = 10   # small number of particles too
dims = 4              # 4 dims

options = {'c1': 0.4, 'c2': 0.3, 'w':0.9}

for r in range(1000):  #simulate doing a LOT of swarm optimizations
    optimizer = ps.single.GlobalBestPSO(n_particles=n_particles, dimensions=dims, options=options,)
    cost, pos = optimizer.optimize(evpeaks_multi, n_processes=4, iters=iters)
```

Eventually get the message: 

`ValueError: Unable to configure handler 'file_default': [Errno 24] Too many open files: '/home/jeremy/Documents/assay_processors/report.log'`

If n_processes is None, this does not happen. 

It is likely this is due to the pool of workers not being destroyed correctly (following the error, a large number of workers are still open and breaking begins closing all those orphans)

**Comment by ljvmiranda921** [comment]
Hmmm, we should definitely fix this, @whzup , what do you think?

**Comment by ljvmiranda921** [comment]
@stale stop
