### ISSUE TITLE
User-provided initial positions (follow-up)

### ISSUE THREAD

**Issue by vkremenetski** [ljvmiranda921/pyswarms#353]
I would like to have some feature where I can initialize the particle positions of the swarm.

I looked at post #119 with regards to this issue but when I tried to use the suggested workaround (optimizer.pos = my_own_positions.copy()) something odd happened: the optimizer returned a best cost that was far higher than the cost that was present at those initial positions. 

This leads me to suspect that either the optimizer doesn't look at the cost at the initial positions of the particles (which would be very odd) or there's something else at play here that's going amiss.

**Comment by ljvmiranda921** [comment]
Hi @vkremenetski , is it possible to provide a working example that reproduces this error?

**Comment by ljvmiranda921** [comment]
@stale stop
