### ISSUE TITLE
how to set the inertia weight 𝜔 dynamically

### ISSUE THREAD

**Issue by brett18618** [ljvmiranda921/pyswarms#355]
Hi, I'd like to set the inertia weight 𝜔 with a linearly decreasing dynamic parameter framework descending from 𝜔𝑚𝑎𝑥 to 𝜔𝑚𝑖𝑛  as follows:
𝜔 = 𝜔𝑚𝑎𝑥 −(𝜔𝑚𝑎𝑥 − 𝜔𝑚𝑖𝑛)/ 𝐼𝑡𝑒𝑟s * 𝐼𝑡𝑒𝑟 
Is it possible to accomplish that?

**Comment by ljvmiranda921** [comment]
stop

**Comment by whzup** [comment]
Hello @brett18618, I don't think it is possible with the vanilla optimizers, but you could always build your own with the building blocks provided by pyswarms 😄. Also, please excuse the long waiting time, we have had some "time issues" in the maintainer team 😞.
