### ISSUE TITLE
from pyswarms.utils.console_utils import cli_print : i try to used this package but it doesn't work could you suggest it alternative 

### ISSUE THREAD

**Issue by uttamkhatri** [ljvmiranda921/pyswarms#358]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Linux]
 - Version [e.g. Ubuntu 16.04]
 - PySwarms Version [e.g. v.0.2.0]
 - Python Version [e.g. 3.6.X]

**Additional context**

**Comment by ljvmiranda921** [comment]
Hi @uttamkhatri , can you provide a reproducible example so that we can further pinpoint where the error is? Thank you!

**Comment by uttamkhatri** [comment]
from pyswarms.utils.console_utils import cli_print

            if i % print_step == 0:
                cli_print(
                    "Iteration {}/{}, cost: {}".format(i + 1, iters, np.min(self.swarm.best_cost)),
                    verbose,
                    2,
                    logger=self.logger,
                )

**Comment by ljvmiranda921** [comment]
Hi @uttamkhatri , I am wondering why you're using `cli_print`. It's not a public-facing function and it's only used when developing PySwarms! Please let me know where you are using it so that I can guide you better!
