### ISSUE TITLE
Giving a callback to the optimize function

### ISSUE THREAD

**Issue by dvida** [ljvmiranda921/pyswarms#359]
Hi!

Thanks for writing such a practical, readable, and well documented library! 

It would be even greater if one could give a callback function to the optimize function which would get called at the end of every loop.

I'm running the PSO on a supercomputer and I'm using many particles. The eval function runs a complex simulation, so it takes a long time to finish an iteration. I would like to be able to check what is the best solution that the PSO is finding at every iteration as a sanity check.

Thanks!
Denis

**Comment by ljvmiranda921** [comment]
Hello @dvida ! Thanks a lot, I'd definitely love to work on this but my greatest blocker is that I don't have much time. It would be nice to have someone take-up on this feature and work on a PR!

**Comment by riyanshk** [comment]
@ljvmiranda921 I would love to work on this PR.

**Comment by ironstein0** [comment]
@ljvmiranda921 Can I pick up this work?

**Comment by ljvmiranda921** [comment]
Hi @ironstein0 ! Gladly! Thanks a lot!

**Comment by Nathan-Naidoo** [comment]
Hello

I think this feature will be of great value. It will benefit my application of pyswarms.
