### ISSUE TITLE
Need Help to Understand some data of your Documentation

### ISSUE THREAD

**Issue by bundasmanu** [ljvmiranda921/pyswarms#360]
Hi guys,

I started this week trying pyswarms.
First of all I would like to thank you for the tremendous contribution you have made to this very interesting and useful project.
Well, I've been analyzing a document of your project, and applying it to my dataset, and according to my data, I didn't realize which parameter should be passed to a function.
The Link to your document is: https://github.com/ljvmiranda921/pyswarms/blob/master/docs/examples/usecases/train_neural_network.ipynb.
I did not understand which parameter should be passed to the function `f` in this statement `cost, pos = optimizer.optimize(f, iters=1000)`. I created a numpy array with [numberParticles, Dimensions], filled with 0's, but i don't think this is the goal.
I would appreciate that you could help me.

**Comment by ljvmiranda921** [comment]
Hi @bundasmanu , let me get back to you tonight! (GMT+8)

**Comment by bundasmanu** [comment]
Hi again,

My only doubt is that in the documentation I mentioned, the function f receives an array as a parameter [nParticles] [dimensions], but when called in optimize, no argument is passed to it, why ??
And if I want to pass more than one parameter to my function f, which is my case, I inevitably have to pass this array, but as in the documentation the call of function f has no parameter, and I am not sure what type of array i need to pass.
Sorry to be boring, but I can't understand what is supposed to pass to method f, because unlike you my function f, gets several parameters, and I need to pass this array, which by your documentation must be implicit in the optimizer.
I would appreciate that you could help me.

**Comment by ljvmiranda921** [comment]
Helllo @bundasmanu , I apologize for my late reply. The value `f` should be a function in this case. Would you mind sharing with me a simple minimum working example so that I can get started?

**Comment by bundasmanu** [comment]
Hello @ljvmiranda921 , i really appreciate your help, but i already solve my problem.
I found an excellent document, that focuses in my question.
[](https://github.com/insideman02468/Miniconda/blob/master/PSO/PySwarms/tutorials/PySwarms_tutorial_Basic_optimization.ipynb).
The link does not seem to be working, but for days it worked.
Thanks for your patience and time
