### ISSUE TITLE
User case of "Feature Subset Selection"

### ISSUE THREAD

**Issue by LouisdeBroglie** [ljvmiranda921/pyswarms#364]
**Describe the bug**
I begin to use the pyswam to solve my real problem . When I follow the user guide, the last step to plot the feature subset. It turns out : 
         
![image](https://user-images.githubusercontent.com/20769762/69228141-0394da00-0bbe-11ea-96ec-3e535e22ccd2.png)

The link is : https://pyswarms.readthedocs.io/en/latest/examples/usecases/feature_subset_selection.html

** solution **

I try to add diag_kind = "hist" in the pairplot func and it appears to be OK !
![image](https://user-images.githubusercontent.com/20769762/69228374-6a19f800-0bbe-11ea-9641-6978f588daa5.png)

**Comment by whzup** [comment]
@LouisdeBroglie What exactly is the problem here?
