### ISSUE TITLE
Passing Discrete Values?

### ISSUE THREAD

**Issue by vectorkt** [ljvmiranda921/pyswarms#365]
Good day,

I have a two-argument function...

f(activation, solver)

...with discrete arguments... 

['logistic','tanh']
['sgd','adam']

...and I'm trying to optimize both of them with a particle swarm.

 Something like:

import pyswarms as ps

bounds1=['logistic','tanh']
bounds2=['sgd','adam']

options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}

optimizer = ps.single.GlobalBestPSO(n_particles=3, dimensions=2, options=options,bounds=[bounds1,bounds2])                              
                                   
cost, pos = optimizer.optimize(f,  iters=1000)

Obviously, it doesn't seem to be working. Any help, suggestions?

**Comment by whzup** [comment]
@vectorkt So you want to pass strings to the optimization function?
