### ISSUE TITLE
Parallel computing problems

### ISSUE THREAD

**Issue by NealWood** [ljvmiranda921/pyswarms#366]
**Describe the bug**
When I use paralell computing by parameter 'n_processes' and set it to '2' or  more over, the code running cost more time than the code which without parelell computing.

**Code**
import pyswarms as ps
import time
from pyswarms.utils.functions import single_obj as fx
options = {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
optimizer = ps.single.GlobalBestPSO(n_particles=50, dimensions=2, options=options)

if __ name __ == '__ main __':
    start = time.time()
    cost, pos = optimizer.optimize(fx.sphere, **n_processes= None**,iters=10000)
    end = time.time()
    print('the time cost is %s s'%(end-start))

_this code costs about 1.15 s.
if I set parameter 'n_processes = 4',it will cost 5.81s,_

**Environment (please complete the following information):**
 - OS: [e.g. Windows10]
 - PySwarms Version [e.g. v.1.1.0]
 - Python Version [e.g. 3.7]

**Comment by sidml** [comment]
I think this happens because the time cost of starting a new process > computation time of function. I tried n_processes > 1 for more complicated functions and it does provide a speedup.

**Comment by NealWood** [comment]
> I think this happens because the time cost of starting a new process > computation time of function. I tried n_processes > 1 for more complicated functions and it does provide a speedup.

**Comment by NealWood** [comment]
> I think this happens because the time cost of starting a new process > computation time of function. I tried n_processes > 1 for more complicated functions and it does provide a speedup.

OK，Thanks for your help!

**Comment by peterfakhry** [comment]
hello there can you please i coded a similar function and n_processes = 4 as well but when i run the code nothing happens!!
