### ISSUE TITLE
How to Change Optimal Value?

### ISSUE THREAD

**Issue by alisaffari97** [ljvmiranda921/pyswarms#369]
# Description

I wanna to use PSO algorithm to find optimal K(number of clusters) value for K-means clustering algorithm.

### What I Did

I used pyswarms.single.GlobalBestPSO function with my own fitness function, the problem is the algorithm find closest cost to zero as the best result, but I wanna  find the closest cost to 1 as best value. How to do that?
Also The algorithm produce float numbers as particle positions, I wanna to produce just integers. How to change that?

**Comment by whzup** [comment]
Hello @alisaffari97 

You can just transform your cost function such that its minimum is when it is closest to 1 (probably you can just add 1 to the cost).
