### ISSUE TITLE
Optimising functions that use arrays 

### ISSUE THREAD

**Issue by georgiek1** [ljvmiranda921/pyswarms#371]
* PySwarms version: 1.1.0
* Python version: 3.7
* Operating System: MacOS 10.14

### Description

I am trying to minimise an output of a PDE model, which uses arrays over a 2D 100x100 grid. I have previously tried using 'pyswarm', but it does not have a parallelisation option, so running it is far too slow and computationally expensive. I have turned to 'pyswarms', but have come across an issue with using arrays.

### What I Did

ValueError: operands could not be broadcast together with shapes (10, 1) (100, 99). The latter (100, 99) is the size of the array of my 'argument', and I assume (10, 1) is the shape of the array of particles as I am using the default number of particles.

Please suggest possible solutions, in particular if there is a way to keep the arrays and not have to introduce many 'for' loops into my PDE code.

Thanks!

**Comment by ljvmiranda921** [comment]
Hi @georgiek1 , thanks for using Pyswarms, let me check on this for now and respond in a while!

**Comment by whzup** [comment]
Hello @georgiek1! Could you provide us with your code? 😄 The error message does not really tell us a lot about where the problem happened😕.

**Comment by georgiek1** [comment]
Hello @whzup, thanks for responding! I am attaching a notebook with my use of pyswarms on a test PDE model. I hope it is clear in itself but let me know if it's not. I would really appreciate knowing if the use of arrays in my model is not compatible with pyswarms or whether there is a way around the error. 
[Pyswarms test.ipynb.zip](https://github.com/ljvmiranda921/pyswarms/files/4492856/Pyswarms.test.ipynb.zip)

**Comment by whzup** [comment]
@georgiek1, I had a look at the code and what I noticed is that your objective function takes the shape of only one particle. If you just define your function like this, have a look at the [inverse kinematics tutorial](https://github.com/ljvmiranda921/pyswarms/blob/master/docs/examples/usecases/inverse_kinematics.ipynb) and its objective function. Notice, that all the particles are processed at once in the function. If you just want to keep your function defined for one particle, you can use the [cost decorator](https://github.com/ljvmiranda921/pyswarms/blob/master/pyswarms/utils/decorators/decorators.py#L6). It is used like this
```python
@ps.cost
def minimise(...):
```
I can't check if it works, since I don't have access to the `VEGFmod_timestep` function. Hope it works :smile: .

**Comment by georgiek1** [comment]
Thanks a lot, I will have a look and let you know if I can rework the objective function and suggested. 
My mistake on the function - I renamed it to chem_timestep but did not update the name where it was called.

**Comment by georgiek1** [comment]
Sorry my mistake - the function it calls should be chem_timestep, I renamed it but did not correct where it is called.

Thanks for the suggestions, I've tried both ways and following the format of the inverse kinematics example is working for me. Using @ps.cost isn't returning the expected optimum but I may have made an error implementing it as I don't fully understand what it is doing. The change in objective function is fine though! 

To make the optimisation faster, I have seen that I can run on several cores using n_processes, but are there any other things to consider with pyswarms? I wondered if the number of particles made a difference, and if for instance you have 10 particles, is there any point in using a machine with >10 cores or will it not make any further difference? 

Thanks again for the help!

**Comment by whzup** [comment]
@georgiek1 What `@ps.cost` does, is it "vectorizes" the function similar to the way in the inverse kinematics example. Thus, you have to design your function for only one particle to work. See [here](https://pyswarms.readthedocs.io/en/latest/api/pyswarms.utils.decorators.html) for the documentation and the expected in- and output for the decorated function.

Regarding the number of particles, if you are looking for an optimal amount in the "mathematical" sense, I think there are some numbers in the original publications (I think it's about 20). I think there are actually more publications that treat the swarm size.

So the multiprocessing at the moment evaluates the objective function in parallel. Every core can run one thread so if you use more than 10 cores, then most of the time you will have 10 evaluations in parallel.

I hope this answers your questions 😄.

**Comment by whzup** [comment]
@georgiek1 May I just add to this that the multiprocessing part in the current version is a little buggy (see #394) and that it's been fixed and will be in the next release. Thus, I'd advise you to get the latest version as soon as it is out if you rely on this feature!

**Comment by georgiek1** [comment]
Thanks so much, super useful info. I'll be sure to use the next release when it comes. Hope to update you at some point in the future with my use of pyswarms!
