### ISSUE TITLE
Citing PySwarms in my work

### ISSUE THREAD

**Issue by Timmenke** [ljvmiranda921/pyswarms#374]
Hi PySwarms team, I've extensively used your package in my work on automatic design of quantum computing hardware: https://arxiv.org/abs/1912.03322. If you like, please add my preprint to the readme as work that is citing you. Great package, I love it!

**Comment by whzup** [comment]
@Timmenke Thanks a lot! We'll gladly add you as soon as we get around to it 😄 The paper looks very interesting by the way!

**Comment by ljvmiranda921** [comment]
Hi @whzup and @Timmenke , let me take point on updating the README. :) Unless @Timmenke wants to open up a Pull Request?

**Comment by Timmenke** [comment]
Thanks a lot for including my paper in the update!
