### ISSUE TITLE
Fully connected topology

### ISSUE THREAD

**Issue by yasirroni** [ljvmiranda921/pyswarms#375]
I'm new in PSO and confused in chosing topologies from pyswarms. This article [Comparative Study of Neighborhood](https://www.researchgate.net/publication/221616406_A_Comparative_Study_of_Neighborhood_Topologies_for_Particle_Swarm_Optimizers) explain it nicely. But, the standard or most used topology (based on the mentioned paper), fully connected topology, seems missing from pyswarms/pyswarms/backend/topology/.

It might be there by setting c or other parameter and using specific topology (or you can explain it in star topology to make it into fully connected topology?), but it would be nice if there is a bundled "fully connected topology" (forced value for some of the parameter or neglect some parameter?).

So, i suggest there is exist:

`from pyswarms.utils.functions.single_obj import fully_connected`

**Comment by whzup** [comment]
Hello @yasirroni! Welcome to PySwarms! So in pyswarms we call the fully connected topology a star topology ([as you can verify for yourself in the code](https://github.com/ljvmiranda921/pyswarms/blob/master/pyswarms/backend/topology/star.py#L61)). I think this has something to do with the naming in the original publication but I'm not entirely sure. Maybe @ljvmiranda921 can say more about the origins of this naming.

**Comment by yasirroni** [comment]
Thank you for the answer. 

Then, it come to the next question. I've already trying  to understand the options but I can't fully understand it. 

> To make a particle affected by all other particle and vice versa in start topology (make it fully connected), what is the options settings? Make it blank {} (as default if no options inputted) or set something into something?

Since c and other parameters set how a particle communicate with their neighbors.

**Comment by whzup** [comment]
@yasirroni There is a description in the [documentation](https://pyswarms.readthedocs.io/en/latest/api/pyswarms.single.html#module-pyswarms.single.global_best). In short, it suffices if you set `c2 > 0`. The parameter `c2` is the social parameter that controls the influence of the neighbouring particles. If you set it to `0` a particle will have no contribution from its neighbours.

**Comment by yasirroni** [comment]
Thank you very much. Silly me trying to find the explanation of each parameters in the code.

So, I'll take:
```
from pyswarms.utils.functions.single_obj import star
options = {'c1': 1, 'c2': 1, 'w':1}
```
as the answer for fully connected default setting.

Thank you very much.

**Comment by ljvmiranda921** [comment]
Hi everyone!
The naming came from the original publication of PSO, as you hinted, you can find it at: J. Kennedy and R.C. Eberhart, "Particle Swarm Optimization," Proceedings of the IEEE International Joint Conference on Neural Networks, 1995, pp. 1942-1948.

I believe this Issue can now be closed :+1: 
Thanks @yasirroni for opening-up the Issue and @whzup for taking point!
