### ISSUE TITLE
Optimizer Pickling not working

### ISSUE THREAD

**Issue by ayhaidar** [ljvmiranda921/pyswarms#381]
I am trying to pickle the optimizer, but it is not working. Error returned:

`PicklingError: Can't pickle <class 'pyswarms.base.base_single.ToHistory'>: attribute lookup ToHistory on pyswarms.base.base_single failed`

Is there an easy way to save the optimizer after optimization finishes?

**Comment by ljvmiranda921** [comment]
Hi @ayhaidar ! Can you help me out by creating a minimum reproducible environment for this? 

We haven't explicitly added a `save` feature for serialization but my assumption is that every class can be pickled. I want to test this assumption out first

**Comment by ayhaidar** [comment]
Hi @ljvmiranda921 , Thanks very much for the quick reply. 

Here is an example:

```
# Import modules
import sys
import numpy as np
import pickle

# Import PySwarms
import pyswarms as ps

print('Running on Python version: {}'.format(sys.version))

def cost_function(I):

    #Fixed parameters
    U = 10
    R = 100
    I_s = 9.4e-12
    v_t = 25.85e-3

    c = abs(U - v_t * np.log(abs(I[:, 0] / I_s)) - R * I[:, 0])

    return c


# Set-up hyperparameters
options = {'c1': 0.5, 'c2': 0.3, 'w':0.3}
# Call instance of PSO
optimizer = ps.single.GlobalBestPSO(n_particles=10, dimensions=1, options=options)
# Perform optimization
cost, pos = optimizer.optimize(cost_function, iters=30)
output = open('optimizer.pkl', 'wb')
pickle.dump(optimizer, output)
output.close()
```

Results for the optimization:

Running on Python version: 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
2020-04-08 08:20:48,454 - pyswarms.single.global_best - INFO - Optimize for 30 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.3}
pyswarms.single.global_best: 100%|██████████|30/30, best_cost=0.423
2020-04-08 08:20:48,913 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 0.42345266706364626, best pos: [0.09827086]

Followed by this error caused when trying to save the optimizer variable:

`PicklingError: Can't pickle <class 'pyswarms.base.base_single.ToHistory'>: attribute lookup ToHistory on pyswarms.base.base_single failed`

**Comment by nishnash54** [comment]
This is one of the drawbacks of using `pickle`, it fails to handle nested classes.
In case you want to store just the history, you should be able to pickle that separately or save to a file in `json` or `csv` format.
If you want to store the `optimizer` object as is and reuse it later, I would recommend a package called [`dill`](https://dill.readthedocs.io/en/latest/dill.html). It can be used as a drop in replacement for pickle and handles nested classes and other dependencies.
