### ISSUE TITLE
DOI Link is broken.

### ISSUE THREAD

**Issue by yasirroni** [ljvmiranda921/pyswarms#383]
**Describe the bug**
DOI Link is broken.

**To Reproduce**
Go to [https://doi.org/joss.00433](https://doi.org/joss.00433
) as explained in read me.

**Expected behavior**
PDF download or paper review

**Solution**
Replace the link with the one in bib: [https://doi.org/10.21105/joss.00433](https://doi.org/10.21105/joss.00433)

**Comment by ljvmiranda921** [comment]
Hi @yasirroni , welcome to Pyswarms! Thanks for catching this, would you like to contribute in this library by making a PR? I can help you out! 😄

**Comment by yasirroni** [comment]
Sure, I'll help as much as I can.
