### ISSUE TITLE
image sources for logo and circuit

### ISSUE THREAD

**Issue by ckastner** [ljvmiranda921/pyswarms#387]
I'm packaging PySwarms for inclusion in the Debian archive. One minor issue I've encountered when building a documentation package is that I can't tell if the [logo](https://github.com/ljvmiranda921/pyswarms/blob/master/docs/pyswarms-header.png) is in its "original" form, or if it's the output of some tool (eg: Adobe Illustrator) based on another source file.

If it's the latter, then Debian requires the original source to be shipped as well. Would it be possible to include the original source file in the repository?

It's not a big issue if not, as I can just build and ship the documentation without it.

Furthermore, there's an image of a [circuit ](https://pyswarms.readthedocs.io/en/latest/examples/usecases/electric_circuit_problem.html) hot-linked. Would it be possible to add this to the repository as well? That would enable offline use of the repository. Or is this a third-party image?

Thanks,
Christian

**Comment by ljvmiranda921** [comment]
Hi @ckastner , thank you so much for this initiative! I appreciate that!
* The logo was an output from Adobe Photoshop, I can't seem to remember where I saved the psd file, which is definitely a shame. Let me look for it and get back to you on Wednesday?
* If not, I can recreate the logo using Inkscape and output it as an SVG file, would that work? 
* The circuit one is related to these issues: #202 #288 #239 #242 maybe @whzup can still remember where he sourced it? If not, I can also recreate it in Inkscape and output as SVG. Would Wednesday work?

Thanks a lot!
Lj

**Comment by ckastner** [comment]
Hi Lj,

* if you can confirm that the original source of the logo is no longer there, then that's fine, too. Then the current PNG becomes the base. Should you ever recreate the logo in Photoshop or some other tool, it would be great if you could include the base  document with which the PNG is created in the source.

* The circuit is not a big deal, either. Our doc building toolchain automatically flags hot-linked images as privacy concerns because opening the docs always pings home to some other site, but I solved this in the current build by simply replacing the embedding with an URL. 

In any case, these are just possible minor improvements, and definitely not blockers (hence why I filed them as feature request). And there's definitely no hurry!

Thanks,
Christian

**Comment by whzup** [comment]
Hey guys. I still have the TikZ source code for the circuit. It's only a few lines of code. @ljvmiranda921 is there a specific place you want the source to be?

**Comment by ljvmiranda921** [comment]
Hi @ckastner ,

Ok, I'd probably go with the route of least effort for now :joy: I'd check in my previous computer if I still have the source. I'll let you know tomorrow or on Wednesday!

It's good that @whzup still has the TikZ source code, since it's not required, up to you if you wish to upload it on this directory: https://github.com/ljvmiranda921/pyswarms/tree/master/docs/examples/usecases . Let me know what you plan to do! 

Thanks everyone and I appreciate this initiative! :bowing_man:

**Comment by ljvmiranda921** [comment]
Gotcha!

**Comment by ljvmiranda921** [comment]
Hi @ckastner ,

1. For the logo, unfortunately, I can't really find the source anymore. 
2. For the circuit image, @whzup made a PR and added the TeX file to `docs/examples/usecases/circuit.tex` hope that works! You can also find the PNG file there.

Let me know if you need anything more :smile: ! Have a good day!

**Comment by ckastner** [comment]
I believe both issues are resolved now.

Thank you, both, for the quick action!
