### ISSUE TITLE
passing parameters

### ISSUE THREAD

**Issue by ghost** [ljvmiranda921/pyswarms#390]
Passing multiple parameters to function not working:

function signature: minFuncHestonWithJumps(x, spot, strikesMat, iR, q, optionTenorsYearFracs,
                               mktOptionPrices0)
x is ndarray with 6 components
args = (SPXSpot, strikes, spotInterestRate, 0.0, optionTenorsYearFracs, mktOptionPrices)
otherStuff = args
import pyswarms as ps
    options = {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
    bounds = ([[-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 1.0, 10.0, 1.0, 1.0, 1.0, 10.0, 1.0, 10.0]])
    optimizerPS = ps.single.GlobalBestPSO(n_particles=10, dimensions=9,
                                          options=options, bounds=bounds)
resPS = optimizerPS.optimize(minFuncHestonWithJumps, iters=100, spot=otherStuff[0], strikesMat=otherStuff[1], iR=otherStuff[2],q=otherStuff[3],
                                      optionTenorsYearFracs=otherStuff[4], mktOptionPrices0=otherStuff[5]
I attempted to follow the example of the Rosenbruck function with parameters in the docs. 

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Linux]
 - Version [e.g. Ubuntu 16.04]
 - PySwarms Version [e.g. v.0.2.0]
 - Python Version [e.g. 3.6.X]

**Additional context**

**Comment by msat59** [comment]
You didn't post the minFuncHestonWithJumps code. Something may be wrong there.

I checked a objective function with parameters and it worked !

**Comment by ljvmiranda921** [comment]
Closing stale issues. Please reopen again if you still encounter this problem
