### ISSUE TITLE
'adjust' velocity handler does not converge

### ISSUE THREAD

**Issue by msat59** [ljvmiranda921/pyswarms#398]
**Describe the bug**
By using vh_strategy='adjust', the optimize method does not converge.

**To Reproduce**
Here is the code:

> options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}
> 
> ndim=2
> max_bound = 5 * np.ones(ndim)
> min_bound = - max_bound
> bounds = (min_bound, max_bound)
> 
> vmax=0.5*(max_bound[0]-min_bound[0])
> vmin=-vmax
> 
> optimizer = ps.single.GlobalBestPSO(n_particles=100, dimensions=ndim, options=options,
>                     velocity_clamp=(vmin,vmax), vh_strategy='adjust', ftol_iter=1000)
> cost, pos = optimizer.optimize(fx.threehump, iters=1000, n_processes=None, verbose=True)
> 
> print(f"Position: {pos}, Cost: {cost}")

output:
`Position: [0.01021064 0.01986428], Cost: 0.0004988469301768021`

**Expected behavior**
Other vh_strategy values or even the default value ("periodic") converge easily. The position should be close to zero after 1000 iterations.

**Environment (please complete the following information):**
 - PySwarms Version 1.1.0
 - Python Version 3.6.x

**Comment by ljvmiranda921** [comment]
I think @whzup is a good fit to tackle this :)

**Comment by whzup** [comment]
Hey @msat59, thanks a lot for testing the package and all its internals 😄! So I remember that I added the [note in the documentation](https://pyswarms.readthedocs.io/en/latest/api/pyswarms.backend.html#module-pyswarms.backend.handlers) for some reason. I think it was explained in some paper but I can't find it at the moment 😕. Have you tried it with other position handling strategies?
Looking at it from a heuristic viewpoint: The default is "periodic" which means the particle appears on the other side. Thus, the velocity may reach across the entire domain. This velocity is then used in the next step which makes it probable that it goes out of bounds again if the particle has "high" inertia (whatever this quantitatively means 😄). Therefore, I'd recommend lowering the inertia `w` and using a less "jumpy" boundary handler as for example "nearest", "shrink", or "intermediate".
(BTW: I also haven't seen any convergence proofs for PSO with position and velocity handlers yet.)

**Comment by whzup** [comment]
Ok, I did some more digging. I think the problem might be caused by the fact that [the velocity is calculated before the position](https://github.com/ljvmiranda921/pyswarms/blob/master/pyswarms/single/general_optimizer.py#L267). This would mean that the velocity after `adjust` is the difference of the unhandled position with the previous position, whereas one would like to have the difference of the handled position with the previous position. I think switching the velocity and position computation in the optimizer should do it.

**Comment by whzup** [comment]
BUT we for the "shrink" strategy we need the velocity so we have to handle this conditionally...
