### ISSUE TITLE
Generalized discrete optimizer for non-binary integer problems? 

### ISSUE THREAD

**Issue by ddathan** [ljvmiranda921/pyswarms#400]
**Is your feature request related to a problem? Please describe.**
I am trying to use PSO to optimize the number of neurons in each layer of a neural network and thus require an integer implementation of the PSO algorithm. As I understand it at the moment there is only an "off the shelf" implementation of a binary version for discrete problems. 

**Describe the solution you'd like**
A generalized implementation of the discrete PSO algorithm for integer variables with user defined bounds.

I understand this may be possible to put together from the base modules so alternatively some direction of how this could be achieved would be greatly appreciated as I have had difficulty when attempting to do so myself.

Many thanks,

**Comment by whzup** [comment]
Hello @ddathan, and welcome to pyswarms!:smile: So I think this is an integer programming problem. The integer aspect may be a bit hard to implement, though. This kind of optimization should be possible but at the moment this needs some additional parts (I'm guessing). A quick Google search yielded [this paper](https://thalis.math.upatras.gr/~elena/papers/LPVInteger.pdf). Maybe this gives some direction as to how to theoretically build it up. Maybe an adjustment to the calculation of the positions and velocities already suffices. I'll have a look at it this week 😃.

**Comment by whzup** [comment]
Hey @ddathan 

I attached the source for a custom optimizer for integer programming. As we have already been thinking about making a tutorial on how to make a custom optimizer this was the perfect excuse to create a template 😄. The custom optimizer just casts all positions and velocities to integers and I'm not 100% how the convergence behaves in this case. I tried to comment on the crucial bits but if you still have questions about the code feel free to ask! 👍
[integer_optimizer.txt](https://github.com/ljvmiranda921/pyswarms/files/4594688/integer_optimizer.txt)

**Comment by ddathan** [comment]
This looks fantastic, many thanks for the great work and support!

**Comment by msat59** [comment]
> Hey @ddathan
> 
> I attached the source for a custom optimizer for integer programming. As we have already been thinking about making a tutorial on how to make a custom optimizer this was the perfect excuse to create a template . The custom optimizer just casts all positions and velocities to integers and I'm not 100% how the convergence behaves in this case. I tried to comment on the crucial bits but if you still have questions about the code feel free to ask! 
> [integer_optimizer.txt](https://github.com/ljvmiranda921/pyswarms/files/4594688/integer_optimizer.txt)

I like this method which is the best one; but the easiest and fastest one is to convert  desired positions to int in the objective function, and leave other as float. So if one is not familiar with writing the custom optimizer, can use below method.

```
def objfun(pos):
    layer1=round(pos[0])   # int number
    layer2=round(pos[1])
    x1 = pos[2]    # float number 
    ...
    ...
    return cost
    
```
