### ISSUE TITLE
Verbose behavior

### ISSUE THREAD

**Issue by nishnash54** [ljvmiranda921/pyswarms#406]
**Describe the bug**
**_verbose_** refers to providing additional information (generally more than what is required). Verbose parameter behaves opposite to the expected conventional behavior.

**To Reproduce**
Default behavior of `verbose` set to `False` but displays the logs. Changing `verbose = True` turns off the logger output.

**Expected behavior**
In my opinion the `verbose` flag is set the opposite way. `verbose = True` must display the information. It must display detailed logging information, in this case the progress bar etc.

**Additional context**
As verbose is a new feature, maybe adding a unit test to ensure the correct behavior when implementing change in the future.

PS. I guess a fix is in progress, created just to keep track.

**Comment by ljvmiranda921** [comment]
Hi @nishnash54 , sorry I wasn’t able to see this last week! That’s so weird behaviour, sure feel free to make a fix!

**Comment by galleguillosbm** [comment]
Hello, I installed the 1.1.0 version using pip. If I call the optimize function passing verbose=True or False, I get the following error:

> 2020-06-11 17:06:26,949 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.1, 'c2': 0.1, 'w': 0.6}
> pyswarms.single.global_best:   0%|          |0/100
> Traceback (most recent call last):
>   File "C:/test/optimization/curve_fit_pso.py", line 140, in <module>
>     cost, pos = optimizer.optimize(cost_function, iters=100, verbose=True)
>   File "C:\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pyswarms\single\global_best.py", line 184, in optimize
>     self.swarm.current_cost = compute_objective_function(self.swarm, objective_func, pool=pool, **kwargs)
>   File "C:\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pyswarms\backend\operators.py", line 239, in compute_objective_function
>     return objective_func(swarm.position, **kwargs)
> TypeError: cost_function() got an unexpected keyword argument 'verbose'

Is there another way to suppress the output log? If don't pass the verbose argument there is no error.
Thanks

**Comment by nishnash54** [comment]
@galleguillosbm The `verbose` functionality is not part of the pypi package (pyswarms 1.1.0). It's part of the new developments in the package.  Sorry for the confusion in the docs.

You can make use of the optimizer without the `verbose` argument, or install the latest **dev** release by cloning the repository from `pyswarms:master` and installing using `python setup.py install`

@ljvmiranda921 The docs point to the changes from development and not the actual pypi package version. Can be confusing for the user. Please have a look.

**Comment by ljvmiranda921** [comment]
Oof noted, thanks for catching this @nishnash54 . Sorry for the confusion, @galleguillosbm !
