### ISSUE TITLE
Save position of each particle in the end so that it can be used as init_pos in next iteration

### ISSUE THREAD

**Issue by SwapniilK099** [ljvmiranda921/pyswarms#407]
Can there be a feature to print/store position of each particle at the end of the program along with its fitness value so that those positions can be used as an initial position of the swarm when next time it is to be run. Otherwise, all the time and learning of the model will be wasted if again particles are initialised randomly. This method can be used further to solve a complex problem with minimum trials. 

If a method gets available to store the position of all particles in PSO, that would be great. @ljvmiranda921

**Comment by ljvmiranda921** [comment]
Hi @SwapniilK099 , there is a [`cost_history` attribute](https://github.com/ljvmiranda921/pyswarms/blob/master/pyswarms/base/base_single.py#L197) in all optimizers if you want to have it saved. 
There's also an [`init_pos` parameter](https://pyswarms.readthedocs.io/en/latest/api/pyswarms.single.html#pyswarms.single.global_best.GlobalBestPSO.init_pos) if you wish to start on a predetermined position

**Comment by SwapniilK099** [comment]
Sir, but how will I access them, the documentation has nothing mentioned about these. 
From the user end, one has access to **optimizer.optimize(obj_fn, init_pos, options)** function and **ps.single.general_optimizer(n_particles, dimensions, bounds, )** . How can I get this pos_history and cost_history of **all the particles** ?

**Comment by ljvmiranda921** [comment]
They’re attributes, so you can access them like optimizer.pos_history

**Comment by SwapniilK099** [comment]
Thanks a lot for the help. It works fine on discrete and continuous. Pls make it available for integer value based PSO also as given in 'issue #400' in a comment. If you could include that integer based PSO in documentation too that would be great. Thanks a lot for this library, its very user friendly.
