### ISSUE TITLE
IndexError: index 5309 is out of bounds for axis 1 with size 1

### ISSUE THREAD

**Issue by JaveJao** [ljvmiranda921/pyswarms#41]
Sir, I'm having problems with the out of bounds error. '5309' is the first element in my y. Here is the complete traceback:

```
IndexError                                Traceback (most recent call last)
<ipython-input-66-107cafabd9c0> in <module>()
     76 
     77 # Perform optimization
---> 78 cost, pos = optimizer.optimize(f, print_step=100, iters=1000, verbose=3)
     79 
     80 def predict(X_train, pos):

~\Anaconda3\envs\tensorflow\lib\site-packages\pyswarms\single\global_best.py in optimize(self, objective_func, iters, print_step, verbose)
    131         for i in xrange(iters):
    132             # Compute cost for current position and personal best
--> 133             current_cost = objective_func(self.pos)
    134             pbest_cost = objective_func(self.personal_best_pos)
    135 

<ipython-input-66-107cafabd9c0> in f(X_train)
     65 def f(X_train):
     66     n_particles = 100
---> 67     j = [forward_prop(X_train[i]) for i in range(n_particles)]
     68     return np.array(j)
     69 

<ipython-input-66-107cafabd9c0> in <listcomp>(.0)
     65 def f(X_train):
     66     n_particles = 100
---> 67     j = [forward_prop(X_train[i]) for i in range(n_particles)]
     68     return np.array(j)
     69 

<ipython-input-66-107cafabd9c0> in forward_prop(params)
     59     # Compute for the negative log likelihood
     60     N = 84 # Number of samples
---> 61     correct_logprobs = -np.log(probs[range(N), Y_train])
     62     loss = np.sum(correct_logprobs) / N
     63     return loss

IndexError: index 5309 is out of bounds for axis 1 with size 1
```

**Comment by JaveJao** [comment]
Here is my complete code:
# Import modules
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from tensorflow.contrib import learn
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn import datasets, linear_model
from sklearn import model_selection
from sklearn import preprocessing

import tensorflow as tf
import pyswarms as ps
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import math
import calendar
import time

%load_ext autoreload
%autoreload 2

# Load the dataset
region = "NCR"
filename = region + ".csv"

x = np.array(pd.read_csv(filename, usecols=[1,2,4,5], header=None))
y = np.array(pd.read_csv(filename, usecols=[3], header=None))

normalized_X = preprocessing.scale(x)

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(
normalized_X, y, test_size=0.2222222222222222, shuffle=False, stratify=None)

# Forward propagation
def forward_prop(params):
    # Neural network architecture
    n_inputs = X_train.shape[1]
    n_hidden = 20
    n_classes = 1

    # Roll-back the weights and biases
    W1 = params[0:80].reshape((n_inputs,n_hidden))
    b1 = params[80:100].reshape((n_hidden,))
    W2 = params[100:120].reshape((n_hidden,n_classes))
    b2 = params[120:121].reshape((n_classes,))

    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    # Compute for the softmax of the logits
    exp_scores = np.exp(logits)
    probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

    # Compute for the negative log likelihood
    N = 84 # Number of samples
    correct_logprobs = -np.log(probs[range(N), Y_train])
    loss = np.sum(correct_logprobs) / N
    return loss

def f(X_train):
    n_particles = 100
    j = [forward_prop(X_train[i]) for i in range(n_particles)]
    return np.array(j)

# Initialize swarm
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}

# Call instance of PSO
dimensions = (4 * 20) + (20 * 1) + 20 + 1
optimizer = ps.single.GlobalBestPSO(n_particles=100, dimensions=dimensions, options=options)

# Perform optimization
cost, pos = optimizer.optimize(f, print_step=100, iters=1000, verbose=3)

def predict(X_train, pos):
    # Neural network architecture
    n_inputs = X_train.shape[1]
    n_hidden = 20
    n_classes = 1

    # Roll-back the weights and biases
    W1 = pos[0:80].reshape((n_inputs,n_hidden))
    b1 = pos[80:100].reshape((n_hidden,))
    W2 = pos[100:120].reshape((n_hidden,n_classes))
    b2 = pos[120:121].reshape((n_classes,))

    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    y_pred = np.argmax(logits, axis=1)
    print(y_pred)
    return y_pred

(predict(X_train, pos) == Y_train).mean()

**Comment by JaveJao** [comment]
Here is my code:

# Import modules
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from tensorflow.contrib import learn
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn import datasets, linear_model
from sklearn import model_selection
from sklearn import preprocessing

import tensorflow as tf
import pyswarms as ps
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import math
import calendar
import time

%load_ext autoreload
%autoreload 2

# Load the dataset
region = "NCR"
filename = region + ".csv"

x = np.array(pd.read_csv(filename, usecols=[1,2,4,5], header=None))
y = np.array(pd.read_csv(filename, usecols=[3], header=None))

normalized_X = preprocessing.scale(x)

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(
normalized_X, y, test_size=0.2222222222222222, shuffle=False, stratify=None)

# Forward propagation
def forward_prop(params):
    # Neural network architecture
    n_inputs = X_train.shape[1]
    n_hidden = 20
    n_classes = 1

    # Roll-back the weights and biases
    W1 = params[0:80].reshape((n_inputs,n_hidden))
    b1 = params[80:100].reshape((n_hidden,))
    W2 = params[100:120].reshape((n_hidden,n_classes))
    b2 = params[120:121].reshape((n_classes,))

    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    # Compute for the softmax of the logits
    exp_scores = np.exp(logits)
    probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

    # Compute for the negative log likelihood
    N = 84 # Number of samples
    correct_logprobs = -np.log(probs[range(N), Y_train])
    loss = np.sum(correct_logprobs) / N
    return loss

def f(X_train):
    n_particles = 100
    j = [forward_prop(X_train[i]) for i in range(n_particles)]
    return np.array(j)

# Initialize swarm
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}

# Call instance of PSO
dimensions = (4 * 20) + (20 * 1) + 20 + 1
optimizer = ps.single.GlobalBestPSO(n_particles=100, dimensions=dimensions, options=options)

# Perform optimization
cost, pos = optimizer.optimize(f, print_step=100, iters=1000, verbose=3)

def predict(X_train, pos):
    # Neural network architecture
    n_inputs = X_train.shape[1]
    n_hidden = 20
    n_classes = 1

    # Roll-back the weights and biases
    W1 = pos[0:80].reshape((n_inputs,n_hidden))
    b1 = pos[80:100].reshape((n_hidden,))
    W2 = pos[100:120].reshape((n_hidden,n_classes))
    b2 = pos[120:121].reshape((n_classes,))

    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    y_pred = np.argmax(logits, axis=1)
    print(y_pred)
    return y_pred

(predict(X_train, pos) == Y_train).mean()

**Comment by ljvmiranda921** [comment]
Hi, 

It seems that the problem is coming from your neural network code and not from the PySwarms module. But I'll try my best to help and interpret your problem:

The `IndexError` is looking for an index or a placeholder, not the value 5309. Can you please show me what the shape of `Y_train` is? What is the value of `Y_train.shape`?

**Comment by JaveJao** [comment]
Hello sir! thanks for your reply. The value of Y_train.shape is (84,1).

**Comment by ljvmiranda921** [comment]
Moreover, in the example found [here](https://pyswarms.readthedocs.io/en/latest/examples/train_neural_network.html) in the documentation, the labels are in a multi-class scheme and of shape `(n_samples, )` (because we have 150 samples, it is `(150, )`. If you print it, it will look like this (where each number corresponds to a particular class):

```python
from sklearn.datasets import load_iris
data = load_iris()
y = data.target
```

The output of `y` is:
```
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
```

**Comment by ljvmiranda921** [comment]
I see, so you need to remove that extra column in your `Y_train`. Can you show me what `Y_train` looks like? Try `print(Y_train)`.

**Comment by JaveJao** [comment]
This is what Y_train looks like, sir:
[[5309]
 [5309]
 [5309]
 [5309]
 [5309]
 [5309]
 [5309]
 [5309]
 [5309]
 [5309]
 [5309]
 [5309]
 [5285]
 [5285]
 [5285]
 [5285]
 [5285]
 [5285]
 [5285]
 [5285]
 [5285]
 [5285]
 [5285]
 [5285]
 [5597]
 [5597]
 [5597]
 [5597]
 [5597]
 [5597]
 [5597]
 [5597]
 [5597]
 [5597]
 [5597]
 [5597]
 [5707]
 [5707]
 [5707]
 [5707]
 [5707]
 [5707]
 [5707]
 [5707]
 [5707]
 [5707]
 [5707]
 [5707]
 [5989]
 [5989]
 [5989]
 [5989]
 [5989]
 [5989]
 [5989]
 [5989]
 [5989]
 [5989]
 [5989]
 [5989]
 [6307]
 [6307]
 [6307]
 [6307]
 [6307]
 [6307]
 [6307]
 [6307]
 [6307]
 [6307]
 [6307]
 [6307]
 [6586]
 [6586]
 [6586]
 [6586]
 [6586]
 [6586]
 [6586]
 [6586]
 [6586]
 [6586]
 [6586]
 [6586]]

**Comment by ljvmiranda921** [comment]
Hmmm, try "flattening" your `Y_train` first. This means that instead of feeding it with a matrix of shape `(84,1)`, you should feed it with a matrix of shape `(84,)`.

This means that:

```python
import numpy as np
Y_train_new = Y_train.ravel()
```

Try using `Y_train_new` as your new input and let's see how it will work.

**Comment by JaveJao** [comment]
Y_train_new is now
[5309 5309 5309 5309 5309 5309 5309 5309 5309 5309 5309 5309 5285 5285 5285
 5285 5285 5285 5285 5285 5285 5285 5285 5285 5597 5597 5597 5597 5597 5597
 5597 5597 5597 5597 5597 5597 5707 5707 5707 5707 5707 5707 5707 5707 5707
 5707 5707 5707 5989 5989 5989 5989 5989 5989 5989 5989 5989 5989 5989 5989
 6307 6307 6307 6307 6307 6307 6307 6307 6307 6307 6307 6307 6586 6586 6586
 6586 6586 6586 6586 6586 6586 6586 6586 6586]
and its shape is (84,). However, the index error still persists, sir :( I really appreciate your help.

**Comment by ljvmiranda921** [comment]
Hmmm, I think it's because you still need to transform your actual labels, 5309 5285 etc into class labels. As I can see in your matrix, you probably have 5/6 different labels. So for all 5309, they should be assigned as 0, for all 5285 would be 1 etc. etc. 

This means that you need to map these numbers into a range from 0 to `num_classes`

**Comment by JaveJao** [comment]
I'm sorry sir but I'm really just a beginner. How can I accomplish that?

**Comment by ljvmiranda921** [comment]
Check [this](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder)

**Comment by JaveJao** [comment]
Sir, is this right?
le = preprocessing.LabelEncoder()
le.fit(Y_train_new)
le.classes_
Y_train_transformed = le.transform(Y_train_new)
le.inverse_transform(le.transform(Y_train_new))
print(Y_train_transformed)

I ran those and here is what I got:
[1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 3
 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 6 6
 6 6 6 6 6 6 6 6 6 6]

**Comment by ljvmiranda921** [comment]
I believe it is correct, would you try that one out in your neural network?

**Comment by JaveJao** [comment]
Sir, it now says "IndexError: index 1 is out of bounds for axis 1 with size 1"

**Comment by ljvmiranda921** [comment]
Can you print the value of `probs`?

**Comment by JaveJao** [comment]
Probs output:
[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]

**Comment by ljvmiranda921** [comment]
I see, that I think is another culprit. The shape of probs should be `(n_samples, n_classes)`. In case of the iris dataset with 150 samples and 3 classes, it is `(150,3)`. 

I think it depends on the neural network configuration that you have set-up. Going back to your code, I realized that the number of classes you set is `1`. Why did you set it as 1? I may be interpreting your problem wrong.

I believe it should be equal to the number of classes that you currently have (I bet it's `7`) given the result of your `Y_train_transform`.

In hindsight, I forgot to ask you what kind of ML problem you are trying to solve, is this a classification problem or a regression one?

**Comment by JaveJao** [comment]
OMG SIR!!! It now worked! thank you very much! 
Why classes = 1? Because I really wanted to predict electricity consumption, which is a numerical value. However, I have another problem that says "array indexes should only be integer or boolean". That's why I tested to predict first the population, which are all integers. I thought that a numerical output is of 1 class only. Am I wrong sir?

**Comment by JaveJao** [comment]
This is a regression problem, sir. I want to output a numerical value, which is the electricity consumption using 4 features namely population, temperature, GDP, and employment rate.

**Comment by ljvmiranda921** [comment]
I see, it worked but I guess we're solving the wrong problem hehehe. I'm sorry I wasn't able to ask you that beforehand. 🍔 

I believe that you are solving a regression problem, not a classification problem. We often use regression to perform forecasting or prediction of future values. Classification is often used for image recognition, etc. 🐱 🐶 🐦 

I suggest you look up how neural networks can be used in regression problems, maybe it can give you an idea. You can still use PySwarms the same way you've been using it before, but only the neural network architecture, and the neural network code will change.

I imagine this is a homework, and you need to train a network using particle swarm optimization. The idea is to have your weights be trained by PSO, and you can use PySwarms for that. To transform your network from classification to regression, you need to do more of research and perhaps find some sample code that helps you on that. 😄 👍 

Hmmm, the regression problem is outside the scope of my use-cases but I could probably open it up some time in the future. I will close this issue for now.

Goodluck!

**Comment by ljvmiranda921** [comment]
In addition, you can come back here again and open another issue if you have created a sample code for a neural network for regression. I can probably help you with that again on how to incorporate PySwarms or PSO in general. 👍

**Comment by JaveJao** [comment]
Thank you for your help, sir! I appreciate it very much. I now opened a new issue hehehe :D I'm just trying to compare the results of BP NN vs PSO NN

**Comment by JaveJao** [comment]
Good day, sir! I just want to thank you for helping me in my assignment. I really appreciate you and most especially, PySwarms <3 I really love it! I am happy that I was able to implement PySwarms in a regression problem using MSE as the loss function. I will not be able to accomplish it if it weren't for your kindness. Once again, thank you very much and may you have a bright future 👍

**Comment by Sanjeeth8733** [comment]
Hello Sir, I'm a total beginner trying this code out and I'm getting an error can you help me out?

CODE
============================
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from tensorflow.contrib import learn
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn import datasets, linear_model
from sklearn import model_selection
from sklearn import preprocessing

import tensorflow as tf
import pyswarms as ps
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import math
import calendar
import time





from IPython import get_ipython
ipython = get_ipython()

if '__IPYTHON__' in globals():
    ipython.magic('load_ext autoreload')
    ipython.magic('autoreload 2')
    
# Load the iris dataset




# Load the dataset
region = "iris"
filename = region + ".csv"

x = np.array(pd.read_csv(filename, usecols=[1], header=None))
y = np.array(pd.read_csv(filename, usecols=[3], header=None))

normalized_X = preprocessing.scale(x)

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(
normalized_X, y, test_size=0.2222222222222222, shuffle=False, stratify=None)
print(Y_train)
import numpy as np
Y_train_new = Y_train.ravel()
le = preprocessing.LabelEncoder()
le.fit(Y_train_new)
le.classes_
Y_train_transformed = le.transform(Y_train_new)
le.inverse_transform(le.transform(Y_train_new))
print(Y_train_new)
print(Y_train_transformed)


# Forward propagation
def forward_prop(params):
    # Neural network architecture
    n_inputs = X_train.shape[1]
    n_hidden = 20
    n_classes = 1

    # Roll-back the weights and biases
    W1 = params[0:80].reshape((n_inputs,n_hidden))
    b1 = params[80:100].reshape((n_hidden,))
    W2 = params[100:120].reshape((n_hidden,n_classes))
    b2 = params[120:121].reshape((n_classes,))

    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    # Compute for the softmax of the logits
    exp_scores = np.exp(logits)
    probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

    # Compute for the negative log likelihood
    N = 84 # Number of samples
    correct_logprobs = -np.log(probs[range(N), Y_train])
    loss = np.sum(correct_logprobs) / N
    return loss

def f(X_train):
    n_particles = 100
    j = [forward_prop(X_train[i]) for i in range(n_particles)]
    return np.array(j)

# Initialize swarm
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}

# Call instance of PSO
dimensions = (4 * 20) + (20 * 1) + 20 + 1
optimizer = ps.single.GlobalBestPSO(n_particles=100, dimensions=dimensions, options=options)

# Perform optimization
cost, pos = optimizer.optimize(f, print_step=100, iters=1000, verbose=3)

def predict(X_train, pos):
    # Neural network architecture
    n_inputs = X_train.shape[1]
    n_hidden = 20
    n_classes = 1

    # Roll-back the weights and biases
    W1 = pos[0:80].reshape((n_inputs,n_hidden))
    b1 = pos[80:100].reshape((n_hidden,))
    W2 = pos[100:120].reshape((n_hidden,n_classes))
    b2 = pos[120:121].reshape((n_classes,))

    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    y_pred = np.argmax(logits, axis=1)
    print(y_pred)
    return y_pred

(predict(X_train, pos) == Y_train).mean()
================================
Error:
File "/anaconda3/lib/python3.6/site-packages/pyswarms-0.3.1-py3.6.egg/pyswarms/single/global_best.py", line 167, in optimize
    self.swarm.position, *kwargs

TypeError: f() takes 1 positional argument but 3 were given
