### ISSUE TITLE
Is calling `logging.config.dictConfig` by default a good idea?

### ISSUE THREAD

**Issue by bek0s** [ljvmiranda921/pyswarms#415]
Hello,

Thanks a lot for this great and easy-to-use library for PSO! I have noticed that some parts of `pyswarms.utils.reporter.Reporter` make calls to `logging.config.dictConfig`. As a result, all messages emitted through `logging.getLogger(__name__).debug/info/warning/etc` in my software are printed to stdout twice because my application also makes a call to `logging.config.dictConfig`. Is there a way to instruct `pyswarms` to never call `logging.config.dictConfig`?

Thank you

**Environment:**
 - OS: Linux
 - Version Debian (Testing)
 - PySwarms Version v.1.1.0
 - Python Version 3.7.6

**Comment by whzup** [comment]
Hello @bek0s, welcome to pyswarms! 😄

I'm sure there is a better solution but I have little experience with logging and @ljvmiranda921 implemented this feature. So I think he'd be the right guy to talk to. Unfortunately, he has phases where he is really invested in work and only sparsely checks pyswarms. Maybe you'll have to be a little bit patient. Do you know a solution that would resolve this issue?

**Comment by ljvmiranda921** [comment]
Hey thanks for taking point on this @whzup ! 

Welcome to pyswarms @bek0s !

Sorry, I'm sparsely checking issues as of this moment. But to answer your question:
* I think the best way to do this is to configure the logger using a yaml file. You can see something similar to [this](https://stackoverflow.com/questions/7507825/where-is-a-complete-example-of-logging-config-dictconfig). You can disable the streams using that for pyswarms only. 
* Refactoring this would definitely take some time. A probable change can be to remove the whole `reporter` module and replace it with [loguru](https://github.com/Delgan/loguru)

Hope it helps! Closing this issue now :+1: We can still continue the conversation here!
