### ISSUE TITLE
Objective function getting multiple values to process (same number of settled n_particles parameter)

### ISSUE THREAD

**Issue by Marconefs** [ljvmiranda921/pyswarms#417]
Objective function getting multiple values to process (same number of settled n_particles parameter)

I thought it was expected to the objective function receives only 1 value(according to the data dimension), but instead it received n_particles values. 

Is this behaviour correct? If so what I have to do, make the objective function returns a list of the output for each entry value?

**Comment by whzup** [comment]
Hello @Marconefs, welcome to pyswarms! This is indeed the "correct" behaviour. If you want it to only take in one value you can use the [cost](https://pyswarms.readthedocs.io/en/latest/api/pyswarms.utils.decorators.html) decorator.

**Comment by ljvmiranda921** [comment]
Closing this issue now
