### ISSUE TITLE
What is the default bounds of the fitness functions?

### ISSUE THREAD

**Issue by Kurt-Liuhf** [ljvmiranda921/pyswarms#418]
Hi, thank you so much for building this interesting library and it's a great piece of work!

I'm now trying to build some applications using the pyswarms and it would great if you can tell me the **default bounds** of the fitness functions. 
And by the way, **how to set the bounds**?  I have used the following test code and some errors occurred.
`optimizer = ps.single.GlobalBestPSO(n_particles=10, dimensions=1, options=options, bounds=((-10, 10)))`

Tons of thanks again.

**Comment by whzup** [comment]
Hello @Kurt-Liuhf, welcome to pyswarms! Maybe [this section of the documentation](https://pyswarms.readthedocs.io/en/latest/api/pyswarms.single.html#pyswarms.single.global_best.GlobalBestPSO.bounds) will answer your question. There are no default bounds so theoretically if you had a function that monotonically decreased from 0 to infinity you'll run into troubles.

**Comment by Kurt-Liuhf** [comment]
Thanks a lot.
