### ISSUE TITLE
Significant Difference

### ISSUE THREAD

**Issue by Zero-maru** [ljvmiranda921/pyswarms#419]
* PySwarms version: 1.1.0
* Python version: 3.6.8
* Operating System: Windows 7 Ultimate

### Description

Hello. I am trying to create a new algorithm using the Global Best Model PSO as a base for my thesis. I have read some examples and tutorials in the documentations. My question is, is there a significant difference in using the global best PSO pre-installed in this module versus the one in the example given? I have observed in my case (mainly due to my hardware) that the global best module is slower in computing compared to the example and since I am planning to run a 10k iteration for almost 10 test functions, it will surely help me if the difference is not that significant. Below is the code found in the example page. Thanks.

### What I Did

```
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Image

import pyswarms.backend as P
from pyswarms.backend.swarms import Swarm
from pyswarms.backend.handlers import BoundaryHandler, VelocityHandler
from pyswarms.backend.topology import Star, Ring, Pyramid
import pyswarms.utils.functions.single_obj as fx

pos_domain = 512
pos_max = pos_domain
pos_min = -1 * pos_domain
particles = 50
dim = 2

np.random.seed(92189122)
fix_pos = np.random.uniform(low = pos_min, high = pos_max, size = (particles, dim))
np.random.seed()

#---------------------------------------
#Set up objective function to be optimized:
test_function = fx.eggholder

#Set up Parameter:
coefficient1 = 1.20
coefficient2 = 1.20
inertia = 0.4

#Set up boundaries:
domain_bound = 512
x_max = domain_bound * np.ones(dim)
x_min = -1 * x_max
my_bounds = (x_min, x_max)


#Set up Handlers:
my_velocityhandler = VelocityHandler(strategy="unmodified")
my_boundaryhandler = BoundaryHandler(strategy="reflexive")
my_clamp = None

#Set up Swarm Options:
my_topology = Star() # The Topology Class
my_options = {'c1': coefficient1, 'c2': coefficient2, 'w': inertia} # arbitrarily set

#Generate initial position of each particle:
init_position = P.generate_swarm(n_particles=particles, dimensions=dim, init_pos=fix_pos)

#Generate initial velocity of each particle (zero):
init_velocity = np.zeros((particles,dim), dtype=int)

#Generate Swarm:
my_swarm = Swarm(position=init_position, velocity=init_velocity, options=my_options)

#Set up number of iterations:
iterations = 1000

#Optimization Loop:
for i in range(iterations):
    # Part 1: Update personal best
    my_swarm.current_cost = test_function(my_swarm.position) # Compute current cost
    my_swarm.pbest_cost = test_function(my_swarm.pbest_pos)  # Compute personal best pos
    my_swarm.pbest_pos, my_swarm.pbest_cost = P.compute_pbest(my_swarm) # Update and store
    
    # Part 2: Update global best
    # Note that gbest computation is dependent on your topology
    if np.min(my_swarm.pbest_cost) < my_swarm.best_cost:
        my_swarm.best_pos, my_swarm.best_cost = my_topology.compute_gbest(my_swarm)
    
    # Print output
    if i%1==0:
        print('Iteration: {} | my_swarm.best_pos: {}'.format(i+1, my_swarm.best_pos))
        print('Iteration: {} | my_swarm.best_cost: {}'.format(i+1, my_swarm.best_cost))
    
    # Part 3: Update position and velocity matrices
    # Note that position and velocity updates are dependent on your topology
    my_swarm.velocity = my_topology.compute_velocity(my_swarm, my_clamp, my_velocityhandler, bounds=my_bounds)
    my_swarm.position = my_topology.compute_position(my_swarm, bounds=my_bounds)
    
print('The best position found by our swarm is: {}'.format(my_swarm.best_pos))
print('The best cost found by our swarm is: {}'.format(my_swarm.best_cost))
```

**Comment by whzup** [comment]
Hello @Zero-maru, welcome to pyswarms! So it seems to me that what you did was just stripping the entire GlobalBestPSO class and removing the logging and history part. If this works for you, you can surely go ahead with this version (which probably also allows you to have more control over the algorithm than the GlobalBestPSO class). To be honest, we have not yet profiled the optimizer classes and we cannot really give any explanation for this performance enhancement. Could you share how significantly the timings vary?

**Comment by Zero-maru** [comment]
@whzup So is this like the GlobalBestPSO class minus the logging and history part? Does that mean that their process are approximately the same? Also, as for timings, when I use the GlobalBestPSO class, a 1000 iteration run for the sphere function will roughly take 1-2 hours. That's why I am on the fence in using said class on my 10k iteration run since it may take at least a day or two in my estimation.

**Comment by whzup** [comment]
It should be more or less that yes. If this version is faster for you, I definitely recommend you go with it. There is not much more necessary functionality in the class than in your code.
I tested it on my hardware, it takes about the same time (in the range of 0.1 to 0.2 seconds) but of course it might be that there are some things that take a lot longer on your hardware.

**Comment by Zero-maru** [comment]
Thank you for your reply. Can I ask on what to do if I want to plot  the best cost value on every iteration in my code? I am still not familiar with the decorator class. Also,

> I tested it on my hardware, it takes about the same time (in the range of 0.1 to 0.2 seconds) 

The GlobalBestPSO class or my own code?

**Comment by whzup** [comment]
> Can I ask on what to do if I want to plot the best cost value on every iteration in my code?

Plot like in plotting a graph or plot like plotting it on the command line? For the first one, you can just use matplotlib because you already have the best position for every iteration, so you have to store them somewhere.

> The GlobalBestPSO class or my own code?

Both, the class takes a little bit longer usually but sometimes it is even faster (of course I'm also using the computer during the computation so it's a little bit skewed).
