### ISSUE TITLE
How to vary inertia during optimisation?

### ISSUE THREAD

**Issue by Ron-Leizrowice** [ljvmiranda921/pyswarms#423]
Hi, new to using Pyswarms, I'm wondering if there is a way to implement variable inertia optimisation using the "GeneralOptimizerPSO" module? I want to decrease the 'w' parameter in options as my optimisation progresses, but I don't know if updating the global variable of 'options' actually changes the optimiser hyperparameters?

**Comment by ljvmiranda921** [comment]
Hi @Ron-Leizrowice , yup updating the global variable options should change the optimizer hyperparameters :smile:

**Comment by Ron-Leizrowice** [comment]
Amazing thank you!

**Comment by Antonio-Nappi** [comment]
could you post a code snippet to show how to change hyperparameters according to the current iterarion?
