### ISSUE TITLE
Optimizing multiple paramters but only one parameter returned

### ISSUE THREAD

**Issue by leocd91** [ljvmiranda921/pyswarms#425]
* PySwarms version: 1.1.0
* Python version: 3.7
* Operating System: windows

### Description

I am trying to optimize multiple parameters but only one parameter returned after optimization.

### What I Did

```
import pyswarms as ps
import numpy as np
# Set-up hyperparameters
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}

def fxtest(x):
    f = x[0]**2 + x[1]**2
    return f
# Call instance of PSO
optimizer = ps.single.GlobalBestPSO(n_particles=2, dimensions=1, options=options)
# Perform optimization
best_cost, best_pos = optimizer.optimize(fxtest, iters=10)
```

Result :
```
2020-10-20 15:12:35,465 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
pyswarms.single.global_best: 100%|██████████|10/10, best_cost=0.139
2020-10-20 15:12:35,480 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 0.13898736381726456, best pos: [0.2663768]
```

**Comment by mamadyonline** [comment]
Hello @leocd91,

I think the behavior is the one expected. You specified the dimension to be 1, so here what you are doing is telling PYSWARMS to optimize the function 'fxtest' as a one dimensional function.

Maybe what you want to do is to set the dimension to 2! Hope this helps

**Comment by leocd91** [comment]
whoopsie my bad.
