### ISSUE TITLE
Typo on train_neural_network use case

### ISSUE THREAD

**Issue by a310883** [ljvmiranda921/pyswarms#428]
**Describe the bug**
There is a typo on pyswarms/docs/examples/usecases/train_neural_network.ipynb. In cells 6 and 9 logits_funciton is written instead of logits_function.

**Expected behavior**
It is expected to use logits_function because that is the defined function.

**Comment by ljvmiranda921** [comment]
Hi @a310883 , thanks for bringing it up! Would you like to open-up a PR for this? :)

**Comment by a310883** [comment]
@ljvmiranda921 Sure thing, I made the PR on #430
