### ISSUE TITLE
Best Parameter Set after Keyboard Interrupt

### ISSUE THREAD

**Issue by iljastas** [ljvmiranda921/pyswarms#442]
Hi,

great package/module. Thanks for that.
Currently, I always get the best cost and percentage of the optimization process.
I would be nice if also the best parameter set would be printed out by a keyboard interruption.
Best regards,
Ilja

**Comment by ljvmiranda921** [comment]
Hi @iljastas! 

Can you tell me more about your use-case? Ideally we don't want the user to easily break the optimization process using a manual input. You can **get the best cost prior to the final iteration by using the cost history property**, `optimizer.cost_history`. It returns an array and you can index it on the iteration of your choice :+1:

**Comment by ljvmiranda921** [comment]
Closing stale issues
