### ISSUE TITLE
How to pass parameters to cost function in GridSearch?

### ISSUE THREAD

**Issue by Antonio-Nappi** [ljvmiranda921/pyswarms#443]
* PySwarms version:1.2
* Python version:3.7
* Operating System: Windows 10

### Description
Hello everybody, Happy new year :)
I want to compute the best hyperparameters for my problem, but my cost function requires some parameters, when I optimize it I can use the "params" dictionary to pass these extra arguments. Can I do the same with RandomSearch method and GridSearch?

**Comment by msat59** [comment]
I'm not sure if I got your question correctly.

Is your question about pyswarms or GridSearch?

**Comment by Antonio-Nappi** [comment]
My question is about pyswarms. Since I can use Gridsearch to find the best hyperparameters for my objective function but my objective function requires some extra inputs, how can I pass these to the function?

**Comment by msat59** [comment]
If you mean passing to pyswarms, you can do it in optimize method. Look at example below:

```
def f_obj(param1, param2):
    # your code
    pass
```

Now you should pass them like this:

```
cost, pos = optimizer.optimize(f_obj, iters=100, param1=x, param2=y)
```

**Comment by Antonio-Nappi** [comment]
Ok, but with Gridsearch how can I do it?

**Comment by msat59** [comment]
> Ok, but with Gridsearch how can I do it?

Google it, search stackoverflow, or sklearn website. :wink:

There is an example in GridSearchCV documentation for SVC()

```
GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 10], 'kernel': ('linear', 'rbf')})
```

**Comment by Antonio-Nappi** [comment]
but this is the GridSearch of sklearn, what about `pyswarms.utils.search.GridSearch`? I'm interested in this function [https://pyswarms.readthedocs.io/en/latest/api/pyswarms.utils.search.html](url).

**Comment by msat59** [comment]
> but this is the GridSearch of sklearn, what about `pyswarms.utils.search.GridSearch`? I'm interested in this function [https://pyswarms.readthedocs.io/en/latest/api/pyswarms.utils.search.html](url).

Shame... that was my bad :cry: 

It seems that GridSearch and RandomSearch don't get obj_fun parameters as **kwargs.

You may be able to use other parameters in your objective function using global variables for now.

**Comment by Antonio-Nappi** [comment]
Don't worry. Yes, it's the same walk-around that I thought.

**Comment by LizzAlice** [comment]
I have a bit of a related question, how did you import GridSearch? When I try to use GridSearch or RandomSearch with `ps.utils.search.random_search.GridSearch(LocalBestPSO, n_particles=100, dimensions=p_size, options=options, objective_func=sobj_fun, iters=10)`, I get the Error _AttributeError: module 'pyswarms.utils' has no attribute 'search'_

**Comment by msat59** [comment]
> I have a bit of a related question, how did you import GridSearch? When I try to use GridSearch or RandomSearch with `ps.utils.search.random_search.GridSearch(LocalBestPSO, n_particles=100, dimensions=p_size, options=options, objective_func=sobj_fun, iters=10)`, I get the Error _AttributeError: module 'pyswarms.utils' has no attribute 'search'_

You can find examples in the documentation, [here](https://pyswarms.readthedocs.io/en/latest/api/pyswarms.utils.search.html)
