### ISSUE TITLE
Altering the update velocity parameter

### ISSUE THREAD

**Issue by Luucccyyyy6** [ljvmiranda921/pyswarms#444]
I'm new to programming, and have found PySwarms could be a potential lifesaver for a Masters module project I'm doing. I'm looking to create a version of the Fitness-Distance-Ratio PSO (Peram, Veeramachaneni and Mohan, 2003). In this algorithm there's an additional part of the update velocity parameter, a 'c3' - which is the 'neighbourhood best', where particles learn from the experience of neighbouring particles with better fitness than them. 'nbest' is the particle j that minimises the equation: Cost(P_j) - Cost (X_i) / |P_j,d - X_i,d|. So that the velocity update has an extra parameter 'c3 * (P_nd - X_id)'. But the update position equation is the same. 

I was wondering if there is a way to change the update velocity equation in order to add in this addition?

**Comment by Antonio-Nappi** [comment]
Since the velocity is update in the topology, I suggest you to create a subclass in order to modify the "update_velocity" method and add the new parameter you need. I'm not a developer of Pyswarms so maybe there is a better solution.

**Comment by Luucccyyyy6** [comment]
@Antonio-Nappi what did you mean by this? how would i modify the method?

**Comment by Antonio-Nappi** [comment]
just implement a subclass of the Star class in Topology script
