### ISSUE TITLE
Different behavior between my optimization loop and optimize

### ISSUE THREAD

**Issue by Antonio-Nappi** [ljvmiranda921/pyswarms#445]
* PySwarms version: 1.3
* Python version: 3.8
* Operating System: Windows 10

### Description
I want to write my own optimization loop, so I just copied and pasted the one present in the documentation. When the code executes the "compute_pbest" method it raises the "TypeError: 'bool' object is not subscriptable", while if I run 
the code with the "optimize" method everything is ok, Why the behavior is different?

**Comment by nikhil-sethi** [comment]
Hi @Antonio-Nappi. Could you include some more information like: Where/which file did you copy the code from?, What was the full python Traceback error(to see where the error is exactly)?
If possible, include a minimal reproducible example that I can test.

**Comment by Antonio-Nappi** [comment]
Hi @nikhil-sethi, I copied the code from the documentation [https://pyswarms.readthedocs.io/en/latest/examples/tutorials/custom_optimization_loop.html](url), and the traceback is 
`
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Users\anton\AppData\Local\Programs\Python\Python38\lib\site-packages\pyswarms\backend\operators.py", line 67, in compute_pbest
    mask_pos = np.repeat(mask_cost[:, np.newaxis], dimensions, axis=1)
TypeError: 'bool' object is not subscriptable

`
The minimal example is 
`
from pyswarms.backend.topology import Star
import pyswarms.backend as P
import numpy as np
from scipy.integrate import odeint

my_topology = Star()
options = {'c1': 2.05, 'c2': 2.05, 'w': 0.7}
my_swarm = P.create_swarm(n_particles=100, dimensions=5, options=options)


def SIR_model(x, t, params):
    S0, I0, C0 = x
    rho, _, tau, beta, gamma = params
    dSdt = - (rho * beta * S0 * I0) / population
    dIdt = (rho * beta * S0 * I0) / population - gamma * I0 - tau * I0
    dCdt = tau * I0
    return [dSdt, dIdt, dCdt]


def cost_SIR_function(parameters, gt, t, N):
    errors = []

    for p in parameters:
        x0 = [N - p[1] - gt[0], p[1], gt[0]]
        Tp = odeint(SIR_model, x0, t, args=(p,))
        Tp = Tp[:,2]
        errors.append(np.sum(np.power((np.divide(np.diff(gt), gt[1:]) - np.divide(np.diff(Tp), Tp[1:])), 2)))
    return errors


population = 100
iterations = 100
values = np.asarray([[99., 1., 0.], [98.35235187, 0.66313927, 0.41021203],
      [97.9261114, 0.43789541, 0.68166383], [97.64605206, 0.28835446, 0.86066395],
      [97.46223831, 0.1895347, 0.97842791], [97.34167879, 0.12443132, 1.05578745],
      [97.26264254, 0.0816261, 1.10655473], [97.21084352, 0.05351857, 1.13984913],
      [97.17690196, 0.03507787, 1.16167507], [97.15466442, 0.02298614, 1.17597894]])
gt = values[:,2]
times = [i for i in range(10)]
for i in range(iterations):
    my_swarm.current_cost = cost_SIR_function(my_swarm.position, gt, times, population)
    my_swarm.pbest_cost = cost_SIR_function(my_swarm.pbest_pos, gt, times, population)
    my_swarm.pbest_pos, my_swarm.pbest_cost = P.compute_pbest(my_swarm)
    if np.min(my_swarm.pbest_cost) < my_swarm.best_cost:
        my_swarm.best_pos, my_swarm.best_cost = my_topology.compute_gbest(my_swarm)
    my_swarm.velocity = my_topology.compute_velocity(my_swarm)
    my_swarm.position = my_topology.compute_position(my_swarm)

`

**Comment by nikhil-sethi** [comment]
Hi @Antonio-Nappi. Thanks for the detailed example and Traceback. The non markdown formatting is no problem! I understood it just fine. For future references though:
```
In markdown you can enclose a 
multi-line code snippet within two sets of triple backticks(```)
```
Regarding the issue: [This] line does a conditional comparison with two *numpy* arrays to yield an array of boolean values(also called a mask). One of these two arrays is the `my_swarm.current_cost` array. At least it should be an array to get the right mask. In your case the current_cost is returned from the `cost_SIR_function` function as a list. And in python using a conditional on two lists yields a single boolean value considering all the elements of that list. So in your case the mask is of type `class <'bool'>` which cannot be indexed on line 67.
I'm including the corrected code with the old lines commented out.
```
def cost_SIR_function(parameters, gt, t, N):
    # errors=[]
    errors = np.array([])

    for p in parameters:
        x0 = [N - p[1] - gt[0], p[1], gt[0]]
        Tp = odeint(SIR_model, x0, t, args=(p,))
        Tp=Tp[:,2]
        # errors.append(np.sum(np.power((np.divide(np.diff(gt), gt[1:]) - np.divide(np.diff(Tp), Tp[1:])), 2)))
        errors = np.append(errors, np.sum(np.power((np.divide(np.diff(gt), gt[1:]) - np.divide(np.diff(Tp), Tp[1:])), 2)))
    return errors
```
Hope this was helpful.

[This]: https://github.com/ljvmiranda921/pyswarms/blob/master/pyswarms/backend/operators.py#L66

**Comment by Antonio-Nappi** [comment]
Oh my god, it was so simple. Thanks both for the issue and the markdown :)
