### ISSUE TITLE
How can I prohibit the function of "storing cost history" to save memory?

### ISSUE THREAD

**Issue by Kurt-Liuhf** [ljvmiranda921/pyswarms#451]
* PySwarms version: 1.3.0
* Python version: 3.8
* Operating System: Ubuntu 16.04

Hi, thank you for building this useful tool. 
I am using the `pyswarms ` to slove some high-dimensional problems. But as the dimension gets larger, more memory are needed. One of a set of my parameters is: 
`c1 = 0.5, c2 = 0.3, w = 0.9, n_particles=2000, dimensions=5120, iters=2000`
The cost function used for testing is **the Sphere**.
I noticed a large amount of memory was used as the optimization step goes on.

But some calculation has been done to estimate the total memory needed in the optimization phase. 
It is about  `2 * bits_of(float) * n_particles * dimensions / (8*1024^3) `Gbs (the main memory consumption not all)
My computer can definitely handle this scale of memory consumption. I guess it is because the `pyswarms` stores the cost history that increases the memory consumption. 

So is there any way to prohibit the function of storing the **cost history** to save the memory?

**Comment by ljvmiranda921** [comment]
For now, I think there's no way to free-up this memory and may not be a priority for now. Closing this issue. Please reopen this if you discovered a way to easily do this! Thanks a lot!
