### ISSUE TITLE
Is there a way of hyperparameter search for function containing both discrete and continuous parameters 

### ISSUE THREAD

**Issue by songyuc** [ljvmiranda921/pyswarms#457]
**Is your feature request related to a problem? Please describe.**

I am working on a optimization problem in which there is a objective function containing both discrete and continuous parameters.

**Describe the solution you'd like**

I hope that we can use both discrete and continuous parameters for a certain objective function.

**Comment by ljvmiranda921** [comment]
So far that functionality doesn't exist. It's not yet in the roadmap but if you're interested to contribute and flesh-out your thoughts on how to best tackle it, that would be really great!
