### ISSUE TITLE
Plotting the velocities of the particles

### ISSUE THREAD

**Issue by Thothore** [ljvmiranda921/pyswarms#461]
* PySwarms version: latest ?
* Python version: latest ?
* Operating System: google colab environment

### Description

I'd like to show the velocities of the particles at each iteration, I already have the particles plotted with the function `plot_surface` / `plot_contour`. Also, maybe it could be an interesting feature to add ?

**Comment by ljvmiranda921** [comment]
Hi @Thothore , I think it's a good feature, it's just that there's no bandwidth to work on it. If you're interested to contribute, then just send a PR this way! :bow:
