### ISSUE TITLE
Replace multiprocessing with multiprocess

### ISSUE THREAD

**Issue by scimax** [ljvmiranda921/pyswarms#480]
Hello everyone,
I just started to use pyswarms, thank you a lot for the nice package. During exploring the features I came across a minor issue.

**Is your feature request related to a problem? Please describe.**
I'm mainly using jupyter notebooks (conda python 3.8, Windows 10), but when running the optimizer with multiple processes, i.e.
```py
cost, pos = optimizer.optimize(rosenbrock_with_args, 1000, n_processes=2, a=1, b=100, c=0)
``` 
the jupyter notebook is busy, but does nothing and the kernel cann't be interrupted. An error is thrown in the console from which the notebook is started, `AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>`. As it turns out, this is a [known problem](https://stackoverflow.com/questions/41385708/multiprocessing-example-giving-attributeerror) of `multiprocessing`, and it is not related to pyswarms by itself.

**Describe the solution you'd like**
Run parallelized optimization from jupyter notebooks. According to the [stack exchange post](https://stackoverflow.com/a/65001152), one solution is to replace `multiprocessing` with the fork `multiprocess`. I've tested it with the example from the multiprocessing documentation and it works out of the box. I see no reason why it should not work with `pyswarms`

**Additional context**
Just replacing `multiprocessing` with `multiprocess` should not be too difficult and, if there is interest, I would provide a PR. What do you think?

Thanks!

**Comment by chrisotoro** [comment]
I'm interested in this. Is there a quick way to implement it?

**Comment by scimax** [comment]
@chrisotoro sorry, I'm pretty busy right now and had no time to look at it so far. But as far as I remember I did exactly what I mentioned above. But if you give me a day, I can look it up.
