### ISSUE TITLE
Address to Lj Miranda

### ISSUE THREAD

**Issue by Riely007** [ljvmiranda921/pyswarms#483]
Hi Lj Miranda, 

I tried to contact you via github and twitter, but seems your DM is not open. :(
I wonder if the "christmAIs" project is still running？

We'd love to make use of it and build something cool relate to web3 and opensource project!

Please let me know if you are interested! 😁

Best wishes,
Riely

**Comment by ljvmiranda921** [comment]
Hi @Riely007 , this repo is not an appropriate venue for this. Saw your email, I'll reply there.
