### ISSUE TITLE
Fix PEP-8 Violations

### ISSUE THREAD

**Issue by jazcap53** [ljvmiranda921/pyswarms#54]
As of 2017-10-28, `flake8` was reporting 397 violations.

A summary of the output of `flake8 --statistics --count pyswarms test` is below:

`6      E125 continuation line with same indent as next logical line`  
`3      E127 continuation line over-indented for visual indent`  
`46    E128 continuation line under-indented for visual indent`
`1      E202 whitespace before ')'  `
`4      E211 whitespace before '('  `
`2      E221 multiple spaces before operator  `
`78    E231 missing whitespace after ','  `
`1      E261 at least two spaces before inline comment  `
`15    E265 block comment should start with '# '  `
`2      E271 multiple spaces after keyword  `
`21    E302 expected 2 blank lines, found 1 ` 
`2      E303 too many blank lines (2)  `
`69    E501 line too long (80 > 79 characters)  `
`1      E502 the backslash is redundant between brackets  `
`10    F401 'logging' imported but unused  `
`1      F841 local variable 'params' is assigned to but never used  `
`108  W291 trailing whitespace  `
`13    W292 no newline at end of file  `
`10    W293 blank line contains whitespace  `
`4      W391 blank line at end of file  `
`397`

**Comment by ljvmiranda921** [comment]
Kinda scary that we incurred these violations. Python's PEP8 is really picky (but for a good reason!) 😕 
Keep it up and thank you so much,@jazcap53 !

**Comment by jazcap53** [comment]
My pleasure! Glad to make myself useful!
