### ISSUE TITLE
Implement Discrete PSO Variants

### ISSUE THREAD

**Issue by ljvmiranda921** [ljvmiranda921/pyswarms#7]
Hi! Thank you for checking out this issue!

Currently, this whole part is pretty much __open__. As of now, I'm planning to give PySwarms four major optimization capabilities: 

* single-objective continuous optimization
* single-objective discrete optimization
* multi-objective optimization, and 
* constrained optimization. 

We've established some grounds on single-objective continuous optimization (with the standard implementations of global-best and local-best PSO). But we haven't done anything yet as for discrete optimization. __Would you like to give us a headstart?__

These are the steps that will be undertaken to close this issue:
1. __Creating an abstract class in the `pyswarms.base` module.__ This will provide a skeleton on how other implementations of the same optimization nature would be written. Take for example how global-best (`pyswarms.single.gbest`) and local-best (`pyswarms.single.lbest`) are inheriting from the class `SwarmBase` (this is the abstract class for single-objective continuous). 

2. __Implementing a standard PSO algorithm inheriting the abstract class written in Step 1.__ This means that a particular discrete PSO optimization algorithm will be implemented while inheriting the base class. 

3. __Writing unit tests and use-case examples__ This is to show how the proposed skeleton and algorithm will be used by the end-user, and of course some unit tests to check its robustness (please check the `tests` directory)

As you can see, the steps is asking for a lot of things. Right now, we're setting this a __low-priority__ because I am currently writing the abstract classes for the other PSO variants. If you think you wanted to be a super-contributor, then go ahead and do all the steps above. 👍 😄 But I believe it would be much better if I set-up a basis first then we iterate from there.

__But perhaps, the best way to contribute on this issue would be the following__:
(note that these contributions don't require pull requests)
* __Propose features on how to implement the abstract classes.__ What do you think are the things to consider when making an abstract class for discrete PSO? You can use your domain-knowledge, and your past experience in handling discrete optimization problems to point out some helpful guides on how to set-up the abstract classes. I can take all of these into consideration when making the first commit in this issue.
* __Suggest discrete PSO implementations that can be implemented in the future.__ If you're planning to do this, please link the paper where it came from (it's okay if there's paywall). It would be better if the research is highly-cited, and is coming from reputable journals in the field of computational intelligence.

That's it for this issue!! For any questions, just drop a comment here!

**Comment by DewaldDeJager** [comment]
Why was this closed?

I have implemented set-based PSO by Langeveld and Engelbrecht but need to make some changes before making a pull request. It needs modifications to the discrete base class as well.

**Comment by ljvmiranda921** [comment]
Oops sorry, I just thought no one will take it so I'll write my own. 😞  

Okay, will open this up! 👍  Thanks @DewaldDeJager!

**Comment by DewaldDeJager** [comment]
Nevermind, I see now that Binary PSO already meets the requirements for this issue to be closed. I will open a new issue some time.

**Comment by ljvmiranda921** [comment]
Ohhhh I see, are the two different? Do you have a link to the paper?

**Comment by ljvmiranda921** [comment]
Hmmm...well the Discrete PSO doesn't have to be just one implementation. Right now we've only implemented a Binary PSO. As long as it falls under the Discrete class, then it's fine! 

At the same time, you can also check the Base Discrete PSO class that I wrote and see if it would fit in general Discrete PSO cases. What do you think, @DewaldDeJager?

**Comment by DewaldDeJager** [comment]
I can't find the exact paper right now but a masters thesis by the same author is available here:
https://repository.up.ac.za/bitstream/handle/2263/55834/Langeveld_Set_2016.pdf
See chapter 4, page 71.

I have looked at the discrete base class and it seems good for in general but it definitely needs changes for the set-based PSO.

Is there a Gitter or IRC channel for pyswarms? Have been wanting to ask or open an issue for a while now. I would be willing to provide help for newcomers there are well.

**Comment by ljvmiranda921** [comment]
Awesome! Okay, do you wanna make a pull request for set-based PSO?
If that's so, then I can leave this issue open. 👍 

Maybe we can check the implementation first and decide if we will refactor the discrete base class (which might affect the already implemented binary PSO) or just go with adding methods to the child class of set-based PSO. 

As of now there is no Gitter nor IRC channel for pyswarms. Personally I believe this is still a small library and still gaining its user base, so issues/questions/etc. can just be opened up in the Issues tab for this repo. 😄

**Comment by ljvmiranda921** [comment]
Hi @DewaldDeJager, I'm closing this issue for now. If you wish to open-up a Pull Request regarding the set-based PSO you've proposed, please open up a new issue and we can converse from there. 👍
