### ISSUE TITLE
Implement Multi-Objective PSO Variants

### ISSUE THREAD

**Issue by ljvmiranda921** [ljvmiranda921/pyswarms#9]
Hi! Thank you for checking out this issue!

Currently, this whole part is pretty much __open__. As of now, I'm planning to give PySwarms four major optimization capabilities: 

* single-objective continuous optimization
* single-objective discrete optimization
* multi-objective optimization, and 
* constrained optimization. 

We've established some grounds on single-objective continuous optimization (with the standard implementations of global-best and local-best PSO). But we haven't done anything yet as for multi-objective optimization. __Would you like to give us a headstart?__

These are the steps that will be undertaken to close this issue:
1. __Creating an abstract class in the `pyswarms.base` module.__ This will provide a skeleton on how other implementations of the same optimization nature would be written. Take for example how global-best (`pyswarms.single.gbest`) and local-best (`pyswarms.single.lbest`) are inheriting from the class `SwarmBase` (this is the abstract class for single-objective continuous). 

2. __Implementing a standard PSO algorithm inheriting the abstract class written in Step 1.__ This means that a particular multi-objective PSO optimization algorithm will be implemented while inheriting the base class. 

3. __Writing unit tests and use-case examples__ This is to show how the proposed skeleton and algorithm will be used by the end-user, and of course some unit tests to check its robustness (please check the `tests` directory)

As you can see, these steps are asking for a lot of things. Right now, we're setting this a __low-priority__ because I am currently writing the abstract classes for the other PSO variants. If you think you wanted to be a super-contributor, then go ahead and do all the steps above. 👍 😄 But I believe it would be much better if I set-up a basis first then we iterate from there.

__But perhaps, the best way to contribute on this issue would be the following__:
(note that these contributions don't require pull requests)
* __Propose features on how to implement the abstract classes.__ What do you think are the things to consider when making an abstract class for multi-objective PSO? You can use your domain-knowledge, and your past experience in handling multi-objective optimization problems to point out some helpful guides on how to set-up the abstract classes. I can take all of these into consideration when making the first commit in this issue.
* __Suggest multi-objective PSO implementations that can be implemented in the future.__ If you're planning to do this, please link the paper where it came from (it's okay if there's paywall). It would be better if the research is highly-cited, and is coming from reputable journals in the field of computational intelligence.

That's it for this issue!! For any questions, just drop a comment here!

### Update (10/5/2017)
- Setting this to high-priority signifying that this is a major undertaking for the development roadmap

**Comment by SioKCronin** [comment]
Hi @ljvmiranda921 ! I've been thinking about this issue a lot, and would love to help implement this. Have you begun work on a base class? I like your idea of getting the base set up first and then iterating. I'll have some time starting next week to cull relevant case studies/applications from the ML space that can help shape the development roadmap.

**Comment by ljvmiranda921** [comment]
Hi @SioKCronin ! Thanks for your help! Unfortunately, I haven't started writing code for the base class here. I hit a bump after writing the Discrete PSO base class. I have some few rough ideas, hopefully I can open up a PR by next week and you can see what I came up with. I believe it will  just be a Base class full of `NotImplementedError`s, but you can check it and see if the "skeleton" is good for other implementations.

**Comment by SioKCronin** [comment]
Hi @ljvmiranda921 The talk went very well, and people were particularly excited about PySwarms. 🎊 
 
I've carved out time this weekend to do a proper literature review, but was wondering if you had come across this paper: 
![image](https://user-images.githubusercontent.com/19956669/31782253-4b7a8134-b4af-11e7-8cec-2df992ee8881.png)

I need to give it a closer read, but I find the transportation context to be quite motivating for MPSO, and their objective functions are clearly articulated.

**Comment by ljvmiranda921** [comment]
Awesome! Glad they liked it, and thanks for including it for your talk and demo! 🍻 

No I haven't read this one, will probably spend the weekend filling myself with various MPSO techniques (+ Constrained optimization in #8 ).  It's true, transportation is a good use-case for MPSO, it would be a nice addition in the docs once we've completed this. It would also be nice to provide built-in objective functions particularly for the MPSO problem. 👍 

Thanks for your help @SioKCronin ! Sorry it took me some time to reply.

**Comment by ljvmiranda921** [comment]
Hi, @SioKCronin , I'll close this one for a while. I'll just wait for any developments on your own project and I'll try to work on this on my own. Hopefully we can share some notes soon! Thanks for this contribution :+1:

**Comment by szhan** [comment]
@ljvmiranda921, are you planning to implement MPSO or CPSO anytime soon?

**Comment by ljvmiranda921** [comment]
Hi, yes it's still part of the pipeline but right now I just want to rewrite the backend so that users can have more control in creating their swarms. That is, you can still use GlobalBestPSO/LocalBestPSO, but if you wish to write your own optimization loop, you can just use PySwarms's native methods.

As for MPSO, I think @SioKCronin is doing a great job in her https://github.com/SioKCronin/SwarmOpt  you might be interested to take a loot.

As for CPSO, as far as I know @EriqLaplus is planning to do some stuff regarding this. What do you think?

**Comment by EriqLaplus** [comment]
@szhan Yeah. It's on my radar to assist in implementing CPSO once the backend is improved. I'm not sure when exactly we will get to CPSO, but I would like to have some CPSO stuff working by the 2018-2019 academic year.

**Comment by SioKCronin** [comment]
I'm planning to have CPSO implemented in my first batch of benchmarks later this month, and will be revisiting MPSO later this summer (I got distracted by my desire to create a scoreboard for single objective optimizers -- I was getting a bit lost in the weeds with all the variants, and pseudo-variants).

I'm doing a big clean-up on this week, but if you want to start a [CPSO implementation](https://github.com/SioKCronin/SwarmOpt/issues/8) @szhan , I can definitely help out with testing and feedback starting next week.

**Comment by d-lowl** [comment]
As far as I can see, not much work has been done for MOPSO yet. I have written a crude implementation of Multiple Objective PSO on top of this codebase, for my own research (following [this paper](https://ieeexplore.ieee.org/abstract/document/1304847)). It serves my case pretty well, but it definetely requires a lot of cleaning up (I've put this up in one day), and must be adjusted to the current workflow of the project; but if the comunity still wants it, I can continue working on it (including writing proper test cases and documentation)

**Comment by ljvmiranda921** [comment]
Hi @d-lowl , I think that would be really helpful! Sure, we can do the cleaning up and we can work together on writing the test cases and documentation! Please ping us here for any updates!

**Comment by d-lowl** [comment]
Well, I got carried away, but I finally had some time today to try and put that together. I'm rather busy most of the time so I thougth I should give an update. https://github.com/d-lowl/pyswarms/tree/multiple-objective

The link above: MOPSO algorithm is added, MultiSwarms class is created (I could not come up with the way to use Swarms class and current topologies template properly, without breaking it, since I use pareto front, there is no notion of best_cost, etc.). best_cost and best_pos are surrogated. So they sit separately. Some docstrings are added for new classes, although not everything is there (also some grammatical errors might be present, as I'm not a native speaker).

Current limitations:

- I use numpy arrays to store the hypercube grid, but ideally sparse arrays should be used. 
- Bounds for objective functions must be set in this implementation. That worked fine for my case, but might be not ideal for other cases.
- Saving to history has been commented out, since, again, there is no proper way to give a current best as a single float, etc. 
- And although the algorithm seems to be working, I have not written tests yet. 

Have a look, and tell what you think about it.

**Comment by ljvmiranda921** [comment]
Hi @d-lowl , let me look at this next week! Sounds awesome!! cc: @whzup @SioKCronin

**Comment by SioKCronin** [comment]
Hi there! Just catching up with this Issue. Would it be helpful @d-lowl for you and I to discuss what you put together and flag areas for possible testing/development that I can support?

**Comment by xud929** [comment]
Hi there! Is there anything new about this issue?
