### ISSUE TITLE
rosenbrock_func does not behave in the same manner like the other utilitiy functions

### ISSUE THREAD

**Issue by mamadyonline** [ljvmiranda921/pyswarms#94]
why does the rosenbrock_func not behave in the same way as the others, especially in the return output ?
 for example calling the utility functions on this array
```
arr = np.random.uniform(size=(7,3))

```
the rosenbrock_func outputs an array of shape (14,) whilst others output an array of shape (7,) which should be the normal behavior. This raises an exception in the optimize method when applying the mask to update  the positions.

Can you tell me if this is a normal thing or if it was done on purpose ?

Thank you

**Comment by ljvmiranda921** [comment]
Oops, it's a bug. Are you interested to send a PR for this? 
There was a problem with indexing and I forgot to sum things up. Top of the head idea:

```python
sum(100.0* np.square(x[1:] - x[:-1]**2.0) + (1 - x[:-1])**2.0)
```

I am wondering why this wasn't detected by our tests... I'll check this further

**Comment by mamadyonline** [comment]
Ok. I will submit a PR for it.
